(function(){var g=function(b){var c=typeof b;if("object"==c)if(b){if(b instanceof Array)return"array";if(b instanceof Object)return c;var a=Object.prototype.toString.call(b);if("[object Window]"==a)return"object";if("[object Array]"==a||"number"==typeof b.length&&"undefined"!=typeof b.splice&&"undefined"!=typeof b.propertyIsEnumerable&&!b.propertyIsEnumerable("splice"))return"array";if("[object Function]"==a||"undefined"!=typeof b.call&&"undefined"!=typeof b.propertyIsEnumerable&&!b.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==c&&"undefined"==typeof b.call)return"object";return c};var h=function(){},j=function(b,c,a){switch(typeof c){case "string":i(c,a);break;case "number":a.push(isFinite(c)&&!isNaN(c)?c:"null");break;case "boolean":a.push(c);break;case "undefined":a.push("null");break;case "object":if(null==c){a.push("null");break}if("array"==g(c)){var d=c.length;a.push("[");for(var e="",f=0;f<d;f++)a.push(e),j(b,c[f],a),e=",";a.push("]");break}a.push("{");d="";for(e in c)Object.prototype.hasOwnProperty.call(c,e)&&(f=c[e],"function"!=typeof f&&(a.push(d),i(e,a),a.push(":"),
j(b,f,a),d=","));a.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof c);}},k={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},l=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g,i=function(b,c){c.push('"',b.replace(l,function(a){if(a in k)return k[a];var b=a.charCodeAt(0),c="\\u";16>b?c+="000":256>b?c+="00":4096>b&&(c+="0");return k[a]=c+b.toString(16)}),'"')};var m,n,o={},p=[],q=!1,r=function(b,c,a){try{var d=o[c[a][0]];if(d&&d[b])d[b](c[a][1])}catch(e){google.ml(e,!1,{cause:"m"+b,index:a,mid:c[a]&&c[a][0]})}};if(google.j)if(google.mc)for(var s=0,t;t=google.mc[s++];){if(29==t[0]){google.j.cfg=t[1];break}}else google.pmc&&(google.j.cfg=google.pmc[29]);var u=null,v=function(){var b=u.value;n=b?eval("("+b+")"):{}};google.initHistory=function(){m=google.kEI;if(u=document.getElementById("hcache")){v();var b=n[m];b&&(google.mc=b)}};
google.med=function(b){if(google.mc||google.pmc){if(google.pmc){for(var c=google,a=[],d=0;d<p.length;++d){var e=p[d];google.pmc[e]&&a.push([e,google.pmc[e]])}c.mc=a}c=google.mc.concat(google.smc||[]);a=0;for(d=c.length;a<d;a++)r(b,c,"dispose"==b?d-a-1:a);"dispose"==b&&(google.mc=null,google.pmc=null,google.smc=null);q="dispose"!=b}};google.register=function(b,c){p.push(b);o[b]=c;if(google.smc&&q)for(var a=0,d=google.smc.length;a<d;a++)google.smc[a][0]==b&&r("init",google.smc,a)};
google.save=function(b,c){if(u){var a;a:{if(google.mc){a=0;for(var d;d=google.mc[a++];)if(d[0]==b){a-=1;break a}}a=-1}0<=a&&(google.mc[a][1]=c,v(),n[m]=google.mc,a=u,d=[],j(new h,n,d),a.value=d.join(""))}};})();
(function(){var e=void 0,f=!0,i=null,k=!1;var l=function(a,b,c){a=a.split(".");c=c||window;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&b!==e?c[d]=b:c=c[d]?c[d]:c[d]={}},aa=function(a,b,c){return a.call.apply(a.bind,arguments)},ba=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,
arguments)}},m=function(a,b,c){m=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?aa:ba;l("google.bindFn",m,e);return m.apply(i,arguments)},o=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}};google.exportSymbol=function(a,b,c){l(a,b,c)};google.exportProperty=function(a,b,c){a[b]=c};l("google.bindFn",m,e);l("google.partial",o,e);var p={i:k,D:k,p:k,opera:k},q={i:k,C:k,k:k,F:k,G:k,H:k,B:k,s:k,w:k,opera:k,v:k},r="",v="",x=function(a){for(var b in p)p[b]=k;for(var c in q)q[c]=k;b=c=i;window.opera?(p.opera=f,q.opera=f,c=b=/Opera[\/\s](\S+)/):0<=a.indexOf("MSIE")?(p.i=f,q.i=f,c=b=/MSIE\s+([^\);]+)(\)|;)/):0<=a.indexOf("WebKit")?(p.p=f,c=/Version\/(\S+)/,0<=a.indexOf("Chrome")?(q.B=f,b=/Chrome\/(\S+)/):0<=a.indexOf("Silk-Accelerated")?(q.s=f,q.v=f,b=c):0<=a.indexOf("Android")&&0>a.indexOf("Mobile")?(q.s=f,b=c):0<=a.indexOf("Android")&&
0<=a.indexOf("Mobile")?(q.w=f,b=c):0<=a.indexOf("Safari")&&(q.k=f,b=c),0<=a.indexOf("iPad")?(q.F=f,q.k||(q.k=f,b=c)):0<=a.indexOf("iPhone")?(q.G=f,q.k||(q.k=f,b=c)):0<=a.indexOf("iPod")&&(q.H=f,q.k||(q.k=f,b=c)),c=/WebKit\/(\S+)/):0<=a.indexOf("Gecko")&&(p.D=f,0<=a.indexOf("Firefox")&&(q.C=f,b=/Firefox\/(\S+)/),c=/rv\:([^\);]+)(\)|;)/);c&&(r=(c=c.exec(a))?c[1]:"");b&&(v=(c=b.exec(a))?c[1]:"",q.i&&(a=document?document.documentMode:e)&&a>parseFloat(v)&&(v=a.toFixed(1).toString()));l("google.browser.engine.IE",
p.i,e);l("google.browser.engine.GECKO",p.D,e);l("google.browser.engine.WEBKIT",p.p,e);l("google.browser.engine.OPERA",p.opera,e);l("google.browser.engine.version",r,e);l("google.browser.product.IE",q.i,e);l("google.browser.product.FIREFOX",q.C,e);l("google.browser.product.SAFARI",q.k,e);l("google.browser.product.IPAD",q.F,e);l("google.browser.product.IPHONE",q.G,e);l("google.browser.product.IPOD",q.H,e);l("google.browser.product.CHROME",q.B,e);l("google.browser.product.ANDROID_TABLET",q.s,e);l("google.browser.product.ANDROID_MOBILE",
q.w,e);l("google.browser.product.KINDLE_FIRE",q.v,e);l("google.browser.product.OPERA",q.opera,e);l("google.browser.product.version",v,e)};x(google.ua||window.navigator.userAgent);
var y=function(a,b){for(var c=0,d=a.replace(/^\s+|\s+$/g,"").split("."),g=b.replace(/^\s+|\s+$/g,"").split("."),h=Math.max(d.length,g.length),j=0;0==c&&j<h;j++){var n=d[j]||"",s=g[j]||"",w=RegExp("(\\d*)(\\D*)","g"),ja=RegExp("(\\d*)(\\D*)","g");do{var t=w.exec(n)||["","",""],u=ja.exec(s)||["","",""];if(0==t[0].length&&0==u[0].length)break;c=((0==t[1].length?0:parseInt(t[1],10))<(0==u[1].length?0:parseInt(u[1],10))?-1:(0==t[1].length?0:parseInt(t[1],10))>(0==u[1].length?0:parseInt(u[1],10))?1:0)||
((0==t[2].length)<(0==u[2].length)?-1:(0==t[2].length)>(0==u[2].length)?1:0)||(t[2]<u[2]?-1:t[2]>u[2]?1:0)}while(0==c)}return c},z=function(a){var b=0==a||1==a?"Height":"Width";if(p.p&&(q.s||q.w||q.v)){if(q.v)return a=window.screen.width,600==a?"Width"==b?600:1024:1024==a?"Width"==b?1024:600:window.screen[b.toLowerCase()];if("Width"==b)return document.documentElement.offsetWidth;b=window.screen.height/window.screen.width;0<b&&b<Number.MAX_VALUE||(b=1);return Math.round(document.documentElement.offsetWidth*
b)}if(0==a||2==a){if(window["inner"+b])return window["inner"+b];if(document.documentElement&&document.documentElement["offset"+b])return document.documentElement["offset"+b]}else return("CSS1Compat"==document.compatMode?document.documentElement:document.body)["client"+b];return 0};l("google.browser.init",x,e);l("google.browser.compareVersions",y,e);l("google.browser.isEngineVersion",function(a){return 0<=y(r,a)},e);l("google.browser.isProductVersion",function(a){return 0<=y(v,a)},e);
l("google.browser.getBrowserDimension",z,e);l("google.browser.Dimension",{HEIGHT_WITH_SCROLLBARS:0,HEIGHT_WITHOUT_SCROLLBARS:1,WIDTH_WITH_SCROLLBARS:2,WIDTH_WITHOUT_SCROLLBARS:3},e);var A=/^(\w+)?(?:\.(.+))?$/,ca=/^#([\w-]+)$/,B=function(a){return(document.getElementById("xjsc")||document.body).appendChild(a)},C=function(a,b){var c=a.match(A),d=document.createElement(c[1]);c[2]&&(d.className=c[2]);b&&(d.innerHTML=b);return d},D=function(a,b){var c;if(c=a.match(ca)){var d=document.getElementById(c[1]);return d?[d]:[]}c=a.match(A);d=c[2]&&RegExp("\\b"+c[2]+"\\b");c=(b||document).getElementsByTagName(c[1]||"*");for(var g=[],h=0,j;j=c[h++];)(!d||d.test(j.className))&&g.push(j);return g},
E=function(a){return a.textContent||a.innerText||""},F=function(a){return a&&a.parentNode&&a.parentNode.removeChild(a)};l("google.dom.append",B,e);l("google.dom.create",C,e);l("google.dom.get",function(a,b){return D(a,b)[0]||i},e);l("google.dom.getAll",D,e);l("google.dom.getText",E,e);l("google.dom.insert",function(a,b,c){return b.parentNode.insertBefore(a,c?b.nextSibling:b)},e);l("google.dom.remove",F,e);
l("google.dom.set",function(a,b){for(var c=1;c<arguments.length;c+=2){var d=arguments[c],g=arguments[c+1],h=a.style;h&&d in h?h[d]=g:d in a?a[d]=g:p.i&&h&&"opacity"==d&&(a.zoom=1,d=(h.filter||"").replace(/alpha\([^)]*\)/,""),isNaN(parseFloat(g))||(d+="alpha(opacity="+100*g+")"),h.filter=d)}return a},e);l("google.dom.isChild",function(a,b,c){c=c||-1;if(a&&b)for(;(a=a.parentNode)&&c--;)if(a==b)return f;return k},e);
l("google.dom.getNodeAttribute",function(a,b){try{var c=a.getAttribute(b);return c?c:""}catch(d){return(c=a.getAttributeNode(b))?c.value:""}},e);var G=function(a,b,c){a.addEventListener?a.addEventListener(b,c,k):a.attachEvent("on"+b,c)},H=function(a,b,c){a.removeEventListener?a.removeEventListener(b,c,k):a.detachEvent("on"+b,c)};l("google.listen",G,e);l("google.unlisten",H,e);var I={},da=function(a,b){return a[1]-b[1]},J=function(a,b,c,d){var g=c===e?f:c,h=c===k,j=b&&b[0]===c;if(a in I){d===e&&(d=k);var n;n="function"==typeof d?d:function(a){return a===d};for(var s=0,w;w=I[a][s++];)if(w=w[0].apply(i,b||[]),h)g=g||w;else if(j&&(b[0]=w),g=w,n(g))return g}return"function"==typeof d?c:g};l("google.msg.listen",function(a){var b=0,c=arguments,d=c.length;1==d%2&&(b=c[d-1]);for(var g=0;g<d-1;g+=2){var h=c[g];I[h]||(I[h]=[]);I[h].push([c[g+1],b]);I[h].sort(da)}},e);
l("google.msg.unlisten",function(a){for(var b=0;b<arguments.length-1;b+=2){var c=I[arguments[b]];if(c)for(var d=arguments[b+1],g=0;g<c.length;++g)if(c[g][0]==d){c.splice(g,1);break}}},e);l("google.msg.send",J,e);var K,ea=window.location.protocol+"//"+window.location.host,L=function(a,b,c){if(!J(32,[a,b,c],0,f))try{RegExp("^("+ea+")?/(url|aclk)\\?.*&rct=j(&|$)").test(a)?b?(google.r=1,b.location.replace(a)):(K||(K=document.createElement("iframe"),K.style.display="none",B(K)),google.r=1,K.src=a):window.location.href=a}catch(d){window.location.href=a}},M=function(){var a=window.location,b=a.hash?a.href.substr(a.href.indexOf("#")+1):"",c=b&&b.match(/(^|&)q=/),d=a.search?a.href.substr(a.href.indexOf("?")+1).replace(/#.*/,
""):"",b=(c?b:d).replace(/(^|&)(fp|tch)=[^&]*/g,"").replace(/^&/,"");return(c?"/search":a.pathname)+(b?"?"+b:"")},fa=function(){var a=window.location;return a.hash?a.href.substr(a.href.indexOf("#")):""},N=function(a,b){var c,d=b?0<=(c=b.indexOf("#"))&&b.substr(c):fa();return(c=d&&d.match("[#&]"+(b?"((q|fp)=|tbs=simg|tbs=sbi)":"fp="))?d.match("[#&]"+a+"=([^&]*)"):(b?b.match(/(\?|$)[^#]*/)[0]:window.location.search).match("[?&]"+a+"=([^&]*)"))?c[1]:i};l("google.nav.go",L,e);
l("google.nav.search",function(a,b){var c=M().match(/[?&][\w\.\-~]+=([^&]*)/g),d={};if(c)for(var g=0,h;h=c[g++];){h=h.match(/([\w\.\-~]+?)=(.*)/);var j=h[2];d[h[1]]=j}for(h in a)a.hasOwnProperty(h)&&(j=a[h],j==i?delete d[h]:d[h]=j);c=["/search?"];g=f;for(h in d)d.hasOwnProperty(h)&&(c.push((g?"":"&")+h+"="+d[h]),g=k);L(c.join(""),e,b)},e);l("google.nav.getLocation",M,e);l("google.nav.getLocationHash",fa,e);l("google.nav.getParam",N,e);
l("google.nav.addParam",function(a,b,c){var d=RegExp("([#?&]"+a+"=)[^&#]*");return b=d.test(b)?b.replace(d,"$1"+encodeURIComponent(c)):b+("&"+a+"="+encodeURIComponent(c))},e);l("google.nav.getQuery",function(){return N("q")},e);var O,P,ga=function(){},Q=function(){return!(!/^mobilesearchapp/.test(N("client"))&&!/^mobilesearchapp/.test(N("source")))},R=[],ha=k,S=function(){if(!("orientation"in window&&!Q()&&window.orientation==O||window.innerWidth==P)){var a=new ga;O=window.orientation;P=window.innerWidth;for(var b=0;b<R.length;b++)window.setTimeout(o(R[b],a),0)}},ia=function(){window.setTimeout(S,10)};l("google.ori.landscape",function(){return!!(window.orientation%180)},e);
l("google.ori.addListener",function(a){for(var b=0;b<R.length;b++)if(R[b]==a)return;R.push(a);ha||(O=window.orientation,P=window.innerWidth,"orientation"in window&&!Q()&&window.addEventListener("orientationchange",S,k),window.addEventListener("resize",Q()?ia:S,k),ha=f)},e);l("google.ori.removeListener",function(a){for(var b=0;b<R.length;b++)if(R[b]==a){R.splice(b,1);break}},e);var T=function(){return"rtl"==document.body.dir||"rtl"==document.dir},U=function(a,b,c){var d=c?"":0;if(p.i){if(d=b.replace(/\-([a-z])/g,function(a,b){return b.toUpperCase()}),d=a.currentStyle&&a.currentStyle[d]||"",!c){if(!/^-?\d/.test(d))return 0;c=a.style.left;a.style.left=d;d=a.style.pixelLeft;a.style.left=c}}else{a=document.defaultView&&document.defaultView.getComputedStyle(a,"");if(p.p&&!a)return d;d=a.getPropertyValue(b);d=c?d:parseInt(d,10)}return d},ka=function(a){var b;if(p.i)(b=a.style.pixelWidth||
0)||(b=a.offsetWidth-U(a,"paddingLeft")-U(a,"paddingRight")-U(a,"borderLeft")-U(a,"borderRight"));else if(b=U(a,"width"),(isNaN(b)||0==b)&&a.offsetWidth)b=a.offsetWidth-U(a,"padding-left")-U(a,"padding-right")-U(a,"border-left-width")-U(a,"border-right-width");return isNaN(b)||0>b?0:b},la=function(a){return a.offsetTop+(a.offsetParent?la(a.offsetParent):0)},V=function(a){return a.offsetLeft+(a.offsetParent?V(a.offsetParent):0)},ma={},W=function(a,b){return!a||!b?k:(ma[b]||(ma[b]=RegExp("(^|\\s)"+
b+"($|\\s)"))).test(a.className)};l("google.style.getComputedStyle",U,e);l("google.style.getHeight",function(a){var b;if(p.i)b||(b=a.offsetHeight-U(a,"paddingTop")-U(a,"paddingBottom")-U(a,"borderTop")-U(a,"borderBottom"));else if(b=U(a,"height"),(isNaN(b)||0==b)&&a.offsetHeight)b=a.offsetHeight-U(a,"padding-top")-U(a,"padding-bottom")-U(a,"border-top-width")-U(a,"border-bottom-width");return isNaN(b)||0>b?0:b},e);l("google.style.getWidth",ka,e);l("google.style.getPageOffsetTop",la,e);
l("google.style.getPageOffsetLeft",V,e);l("google.style.getPageOffsetStart",function(a){return V(a)+(T()?ka(a):0)},e);l("google.style.getColor",function(a){return""+U(a,"color",f)},e);l("google.style.hasClass",W,e);l("google.style.isRtl",T,e);l("google.style.addClass",function(a,b){if(a&&b&&!W(a,b)){var c=""==a.className?[]:a.className.split(/\s/);c.push(b);a.className=c.join(" ")}},e);
l("google.style.removeClass",function(a,b){if(W(a,b)){for(var c=a.className.split(/\s/),d=c.length-1;0<=d;d--)c[d]==b&&c.splice(d,1);a.className=c.join(" ")}},e);var X={},Y="&,&amp;,<,&lt;,>,&gt;,\",&quot;,',&#39;,{,&#123;".split(","),na=function(a){a||(a=window.event);return a.target||a.srcElement},oa=function(a){a.style.display="none";X[a.id]&&H(document.body,"click",X[a.id])};l("google.util.escape",function(a){for(var b=0;b<Y.length;b+=2)a=a.replace(RegExp(Y[b],"g"),Y[b+1]);return a},e);l("google.util.unescape",function(a){for(var b=0;b<Y.length;b+=2)a=a.replace(RegExp(Y[b+1],"g"),Y[b]);return a},e);l("google.util.eventTarget",na,e);
l("google.util.stopPropagation",function(a){a=a||window.event;p.i?a.cancelBubble=f:a.stopPropagation&&a.stopPropagation()},e);l("google.util.getSelection",function(){try{return window.getSelection&&window.getSelection().toString()||document.selection&&document.selection.createRange&&document.selection.createRange().text}catch(a){}return""},e);l("google.util.xjsol",function(a){if(google.sc&&(a=google.sc[a])){for(var b=0;b<a.cb.length;b++)a.cb[b]();a.cb=[]}},e);
l("google.util.xjsl",function(a,b){var c=google.sc[a];c&&(c.dl?b&&b():(b&&c.cb.push(b),google.dlj(c.u),c.dl=f))},e);l("google.util.togglePopup",function(a){var b=document.getElementById(a);if(b)if("none"==b.style.display){b.style.display="";var c=k;X[a]=function(){c?oa(b):c=f};G(document.body,"click",X[a])}else oa(b)},e);
l("google.util.rateLimitFunction",function(a,b,c,d){var g=0,h=k,j=i;return function(){var n=google.time();h?j=Array.prototype.slice.call(arguments,0):n-g>=c?(g=n,b.apply(a,arguments)):d&&(n=c-(n-g),h=f,j=Array.prototype.slice.call(arguments,0),setTimeout(function(){h=k;g=google.time();b.apply(a,j)},n))}},e);l("google.util.isQueryEmpty",function(a){return!a||!a.replace(/\s+|\u3000+/g,"")},e);
l("google.util.arrayIndexOf",function(a,b,c){if(Array.prototype.indexOf)return Array.prototype.indexOf.call(a,b,c);for(c=c==i?0:0>c?Math.max(0,a.length+c):c;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},e);l("google.util.logVisibilityChange",function(a,b,c,d,g,h,j){for(var g=h||"",j=j||"",h=b.length,n=[],s=0;s<h;++s)n.push("0"+google.getEI(d&&d[s]?d[s]:c)+","+b[s]);google.log(g,j+"&ved="+a+"&vet="+n.join(";"),"",c)},e);var Z=function(a,b,c){var d=RegExp("([?&])"+b+"=.*?(&|$)"),a=a.replace(/^([^#]*)(#|$)/,function(a,b){return b});return!a.match(d)&&""!=c?a+"&"+b+"="+c:a.replace(d,function(a,d,j){return c?d+b+"="+c+j:j?d:""})};l("google.srp.isSerpLink",function(a){return/(search|images)/.test(a.href)},e);l("google.srp.isSerpForm",function(a){return/\/search$/.test(a.action)},e);
l("google.srp.updateLinksWithParam",function(a,b,c,d){var g=document.getElementsByTagName("A");google.base_href=Z(google.base_href,a,b);for(var h=0,j;j=g[h++];)if(c(j)){var n=p.i?j.innerHTML:e;j.href=Z(j.href,a,b);n!=e&&(j.innerHTML=n)}for(h=0;c=document.forms[h++];)if(d(c)){for(j=g=0;n=c.elements[j++];)n.name==a&&(g=1,""!=b?n.value=b:n.parentNode.removeChild(n));!g&&""!=b&&(g=document.createElement("input"),g.type="hidden",g.value=b,g.name=a,c.appendChild(g))}},e);
l("google.srp.qs",function(a){if(a=na(a)){for(;!W(a,"qs");)if(a=a.parentNode,!a||a==document.body)return;var b=document.getElementsByName("q"),c=b&&b[0],b=document.getElementById("tsf-oq");c&&b&&window.O&&(c=c.value,b=E(b),c&&c!=b&&(b=Z(a.href,"q",encodeURIComponent(c)),a.href=Z(b,"prmd","")))}},e);var $=function(a,b,c,d){this.a=a;this.J=b;this.g=i;this.o=c||0;this.K=d||function(){return f};a.getAttribute("aria-label")==i&&a.setAttribute("aria-label",b);this.n=m(this.L,this);this.h=m(this.M,this);G(this.a,"mouseover",this.n);G(this.a,"mouseout",this.h);G(this.a,"focus",this.n);G(this.a,"focusin",this.n);G(this.a,"blur",this.h);G(this.a,"focusout",this.h);G(this.a,"mousedown",this.h);G(this.a,"click",this.h);G(this.a,"keydown",this.h)};
$.prototype.destroy=function(){clearTimeout(this.A);clearTimeout(this.z);this.I();H(this.a,"mouseover",this.n);H(this.a,"mouseout",this.h);H(this.a,"focus",this.n);H(this.a,"focusin",this.n);H(this.a,"blur",this.h);H(this.a,"focusout",this.h);H(this.a,"mousedown",this.h);H(this.a,"click",this.h);H(this.a,"keydown",this.h)};$.prototype.L=function(){this.K()&&(window.clearTimeout(this.z),this.A=window.setTimeout(m(this.N,this),130))};
$.prototype.M=function(){window.clearTimeout(this.A);this.z=window.setTimeout(m(this.I,this),130)};
$.prototype.N=function(){if(!this.g){this.g=C("div",this.J);this.m=C("div");this.g.style.cssText="background:#2d2d2d;border:1px solid;border-color:#fff;box-shadow:1px 2px 4px rgba(0,0,0,0.2);box-sizing:border-box;color:#fff;display:block;font-size:11px;font-weight:bold;height:29px;line-height:29px;padding:0 10px;position:absolute;text-align:center;transition:opacity 0.13s;white-space:nowrap;visibility:hidden;z-index:2000;";p.WEBKIT?this.g.style.cssText+="-webkit-box-shadow:0px 1px 4px rgba(0,0,0,0.2);-webkit-box-sizing:border-box;-webkit-transition:opacity 0.13s;":
p.GECKO?this.g.style.cssText+="-moz-box-shadow:0px 1px 4px rgba(0,0,0,0.2);-moz-box-sizing:border-box;-moz-transition:opacity 0.13s;":p.OPERA&&(this.g.style.cssText+="-o-transition:opacity 0.13s;");this.m.style.cssText="border:6px solid;border-color:#fff transparent;border-top-width:0;content:'';display:block;font-size:0px;height:0;line-height:0;position:absolute;top:-6px;width:0;";var a=C("div");a.style.cssText=this.m.style.cssText;a.style.top="1px";a.style.left="-6px";a.style.borderColor="#2d2d2d transparent";
this.m.appendChild(a);this.g.appendChild(this.m);this.a.parentNode?this.a.parentNode.appendChild(this.g):this.a.offsetParent?this.a.offsetParent.appendChild(this.g):document.body.appendChild(this.g);var a=this.a.offsetWidth,b=this.a.offsetLeft,c=this.g.offsetWidth;if(0==this.o){this.g.style.left=a/2-c/2+b+"px";var d=V(this.g);d+c>z(3)?this.g.style.left=b+a-c+1+"px":0>d&&(this.g.style.left=b-1+"px")}else d=T(),this.g.style.left=3==this.o||1==this.o&&d?b+a-c+1+"px":b-1+"px";this.g.style.top=this.a.offsetTop+
this.a.offsetHeight+5+"px";0==this.o?this.m.style.left=this.a.offsetLeft+this.a.offsetWidth/2-this.g.offsetLeft-1-6+"px":(a=T(),3==this.o||1==this.o&&a?this.m.style.right="18px":this.m.style.left="18px");this.g.style.visibility="visible"}};$.prototype.I=function(){this.g&&(F(this.g),this.g=i)};l("google.tooltip.Alignment",{CENTER:0,START:1,LEFT:2,RIGHT:3},e);l("google.tooltip.Tooltip",$,e);$.prototype.destroy=$.prototype.destroy;l("google.xhr",function(){var a=i;if(window.XMLHttpRequest)try{a=new XMLHttpRequest}catch(b){}if(!a)for(var c=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],d=0,g;g=c[d++];)try{a=new ActiveXObject(g);break}catch(h){}return a},e);})();
(function(){var ca=void 0,n=!0,o=null,u=!1,la,pa,ra,sa,ta,ua,za,Aa,Ba,Ca,Da,Ea,Ga,Ha,Ia,Ja,Ka,La,Ma,Oa,Pa,Qa,Ra,Sa,Ta,Wa,Xa,Ya,Za,$a,ab,bb,cb,db,eb,fb,gb,hb,ib,jb,kb,lb,mb,qb,rb,sb,tb,ub,vb,wb,xb,yb,zb,Ab,Bb,Cb,Db,Eb,Fb,Gb,Hb,Ib,Jb,Kb=/^[6-9]$/,Lb={EMPTY:0,Eg:1,we:2},Mb={IE:0,GECKO:1,OPERA:2,CHROME:3,SAFARI:4,WEBKIT:5,rj:6,kj:7},Nb={DONT_CARE:1,xg:2,yg:3},Ob={Hf:0,hi:1,If:2},w={Cj:0,oj:114,gf:115,hf:116,uh:117,jf:118,kf:119,lf:120,of:121,Fh:122,qf:123,sf:124,Hh:125,wj:230,tf:126,uf:127,vf:128,wf:129,nj:231,oh:130,
qh:131,pj:237,sj:132,Bh:134,tj:189,vj:246,Eh:133,xj:184,Mh:173,vh:135,xh:136,zh:137,Ih:138,Kh:139,wh:140,yh:141,Ah:142,Ch:240,Jh:143,Lh:144,sh:145,qj:146,mf:147,Bj:148,mj:150,lj:191,zj:245,Gh:151,RENDERER:152,nf:153,th:154,$e:155,Dh:156,yj:157,rf:158,Ze:159,xf:160,ef:149,uj:256},Rb={ff:161,yf:162};
(function(){function a(a){for(var d=[],b=0,g;g=a[b++];)d.push(e(g));return d}function c(a){var b="";if(a)for(var h=0,g;g=a[h++];)(g=d[g])&&(b+=g);return b}function j(a){return a.Ta()+c(a.Ua())}function e(a){return a.api||{a:a.vb,b:a.Y,c:a.Ta,d:a.B,e:a.Ua,f:a.oi,g:a.ni,h:function(){return j(a)},i:a.Ga,j:a.Wc}}var i=/\D+$/,d={},b={};(function(){b.a=16;b.b=8;b.c=7;b.d=42;b.e=9;b.g=12;b.i=14;b.j=18;b.l=13;b.m=5;b.n=38;b.p=39;b.q=22;b.r=4;b.s=10;b.t=2;b.u=17;b.v=15;b.w=21;b.x=11;b.y=25;b.z=3;b.A=29;b.C=
33;b.D=40;b.E=36;b.F=35;b.G=26;b.I=1;b.J=37;b.K=30;b.L=19;b.N=32;b.P=20;b.Q=27;b.R=28;b.S=24;b.T=23;b.U=41;b.V=31;for(var a in b)d[b[a]]=a})();la=function(a){var d={};if(a)for(var b=0;b<a.length;++b)d[a[b]]=n;return d};pa=function(d){var b=a(d.ha());return d.api||{a:d.ia,b:function(){return b}}};ra=function(a){return a?(a=a.toLowerCase(),"zh-tw"==a||"zh-cn"==a||"ja"==a||"ko"==a):u};sa=function(){return(new Date).getTime()};ta=function(a){var d=[];if(a)if("string"==typeof a){if(a=a.match(i))for(var a=
a[0],h=0,g;h<a.length;h++)g=a.charAt(h),d.push(b[g])}else return a;return d};ua=c;za=j})();
var Sb=function(){return{Ya:function(){return{Fa:"hp",$b:"google.com",dc:"",Ka:"en",Lb:"",Nb:"",Pa:"",authuser:0,Qa:"",ob:u,qd:"",Ra:"",xa:0,Ve:o,mb:u,nb:u,Se:u,Mb:u,ua:la([19,5,0]),Me:u,Md:u,Zc:n,Rb:10,Kd:n,jd:u,$c:u,Nd:u,yb:n,yc:u,Ic:500,Ld:n,md:u,fc:"",Pe:"//www.google.com/textinputassistant",Qe:3,Ne:u,Na:u,Qc:n,Rc:u,La:u,zb:u,Dc:u,Cc:u,Va:1,Bc:n,Ab:n,lb:u,Cb:u,Oc:10,jb:u,He:0,Oe:u,Pc:n,Ac:u,Wb:document.body,nd:n,od:o,gc:{},ta:{},Ie:{},Re:0,Lc:u,dd:n,wa:u,Kc:u,Ue:1,Ge:1,spellcheck:u,Nc:u,Jb:"Search",
Ea:"I'm  Feeling Lucky",Sc:"",Hb:"Learn more",Tb:"Remove",Sb:"This search was removed from your Web History",rd:"",Mc:0,Da:"",eb:"",isRtl:u,kb:"absolute",Fb:u,hd:u,Ib:o,Gb:n,Te:0,Qb:[0,0,0],gd:[0],Kb:0,kd:u,ld:1,Db:"",Uc:"",Tc:"",Je:o,Le:"",Ke:"",Yb:{},Yc:n}},normalize:function(a){return!a?o:{a:a.Fa,b:a.$b,c:a.dc,d:a.Ka,e:a.Lb,f:a.Nb,g:a.Pa,h:a.Qa,i:a.xa,j:a.mb,k:a.nb,l:a.ua,n:a.Me,q:a.Rb,r:a.Zc,s:a.Kd,t:a.jd,u:a.Nd,v:a.yb,w:a.Ld,x:a.md,y:a.Na,z:a.La,aa:a.Dc,ab:a.Cc,ac:a.Va,ae:a.Cb,af:a.Oc,ag:a.Ue,
aj:a.Ge,ak:a.spellcheck,al:a.Nc,am:a.Jb,an:a.Ea,ao:a.Hb,ap:a.Tb,aq:a.Sb,ar:a.Da,as:a.eb,at:a.isRtl,av:a.hd,aw:a.Ib,ax:a.Te,ay:a.Md,az:a.Bc,ba:a.Ab,bb:a.Fb,bc:a.Qb,bd:a.Ve,bf:a.kd,bg:a.authuser,bh:a.ld,bi:a.lb,bj:a.$c,bk:a.Se,bo:a.Ne,bq:a.jb,br:a.fc,bs:a.Db,bt:a.zb,bu:a.He,bv:a.Oe,bx:a.Pc,bz:a.Kb,ca:a.Wb,cb:a.Qc,cc:a.Rc,cd:a.Sc,ce:a.yc,cf:a.Ic,cg:a.gc,ch:a.Ac,ci:a.od,ck:a.Re,cl:a.gd,cm:a.kb,cn:a.nd,cp:a.Lc,cq:a.qd,cr:a.dd,cs:a.Pe,ct:a.ob,cu:a.Mb,cv:a.Kc,cw:a.rd,cz:a.Qe,da:a.Uc,db:a.Tc,de:a.Yb,df:a.Yc,
dg:a.ta,dh:a.Ie,di:a.Je,dj:a.Le,dk:a.Ke,dl:a.Ra,dm:a.Gb,dn:a.wa,"do":a.Mc}},translate:function(a){return{Fa:a.a,$b:a.b,dc:a.c,Ka:a.d,Lb:a.e,Nb:a.f,Pa:a.g,Qa:a.h,xa:a.i,mb:a.j,nb:a.k,ua:a.l,Me:a.n,Rb:a.q,Zc:a.r,Kd:a.s,jd:a.t,Nd:a.u,yb:a.v,Ld:a.w,md:a.x,Na:a.y,La:a.z,Dc:a.aa,Cc:a.ab,Va:a.ac,Cb:a.ae,Oc:a.af,Ue:a.ag,Ge:a.aj,spellcheck:a.ak,Nc:a.al,Jb:a.am,Ea:a.an,Hb:a.ao,Tb:a.ap,Sb:a.aq,Da:a.ar,eb:a.as,isRtl:a.at,hd:a.av,Ib:a.aw,Te:a.ax,Md:a.ay,Bc:a.az,Ab:a.ba,Fb:a.bb,Qb:a.bc,Ve:a.bd,kd:a.bf,authuser:a.bg,
ld:a.bh,lb:a.bi,$c:a.bj,Se:a.bk,Ne:a.bo,jb:a.bq,fc:a.br,Db:a.bs,zb:a.bt,He:a.bu,Oe:a.bv,Pc:a.bx,Kb:a.bz,Wb:a.ca,Qc:a.cb,Rc:a.cc,Sc:a.cd,yc:a.ce,Ic:a.cf,gc:a.cg,Ac:a.ch,od:a.ci,Re:a.ck,gd:a.cl,kb:a.cm,nd:a.cn,Lc:a.cp,qd:a.cq,dd:a.cr,Pe:a.cs,ob:a.ct,Mb:a.cu,Kc:a.cv,rd:a.cw,Qe:a.cz,Uc:a.da,Tc:a.db,Yb:a.de,Yc:a.df,ta:a.dg,Ie:a.dh,Je:a.di,Le:a.dj,Ke:a.dk,Ra:a.dl,Gb:a.dm,wa:a.dn,Mc:a["do"]}}}},Tb=/<\/?(?:b|em)>/gi,Ub={Ug:8,ze:9,ye:13,Id:27,Aj:32,Rg:37,Tg:38,Sg:39,Qg:40,Vg:46},K=function(){var a=Aa,c=0,
j={},e={},i={},d={},b={};return{Th:function(){return c++},Pf:function(a,d,h){e[a]=h;b[a]=[d]},register:function(c,l,h){var g=d[c];g?g!=a&&(d[c]=a):d[c]=h;(g=b[c])?g.push(l):b[c]=[l];i[l]=h},nh:function(){return b},Ya:function(b,c){var h=j[b];return h?h:(h=e[b])?j[b]=h():!c?(h=d[b],!h||h==a?o:h()):(h=i[c])?h():o}}}(),Vb=function(a,c,j,e,i,d){function b(){if(B)for(var a=0,d;d=E[a++];)d.fa&&d.fa()}function k(a){for(var d in a){var b=d,g=a[b];if(g!=f.ff)if(q[b]){for(var p=m[b]||[],h=0,r=ca;h<g.length;++h)(r=
l(b,g[h]))&&p.push(r);m[b]=p}else(g=l(b,g))&&(s[b]=g)}}function l(a,d){var b;if(d&&d instanceof Object)b=d;else if(b=v.Ya(a,d),!b)return o;if(b.pd){var f=b.pd();if(f)for(var g=0,p,h,s;p=f[g++];){s=u;h=p.B();if(q[h]){if(s=t[h]){s.push(p);continue}s=n}t[h]=s?[p]:p}}z.push([b,a]);E.push(b);b.ga&&b.ga(j,e);return b}function h(a){for(var b=0,d=0,f;f=z[d++];)f[0]==a&&(b=f[1]);return b}function g(a,b){var d=Ba(a.B(),p),f=Ba(b.B(),p);return 0>d?1:0>f?-1:d-f}var f=Rb,q=la([w.Ze,w.$e,w.ef,w.nf,w.th,w.RENDERER,
w.Dh,w.Gh,w.rf,w.xf]),r=[w.sh,w.uh,w.jf,w.kf,w.tf,w.gf,w.hf,w.lf,w.mf,w.of,w.Eh,w.Fh,w.qf,w.sf,w.Hh,w.uf,w.vf,w.wf],p=[w.uf,w.ef,w.Bh,w.qf,w.of,w.tf,w.jf,w.gf,w.vf,w.xf,w.Mh,w.kf,w.hf,w.RENDERER,w.nf,w.wf,w.lf,w.sf,w.rf,w.$e,w.qh,w.oh,w.mf,w.yh,w.Ah,w.zh,w.Ch,w.Jh,w.Ih,w.Lh,w.Kh,w.wh,w.vh,w.xh],s={},m={},t={},z=[],E=[],B=u,v=K,D={O:function(a){b();for(var d=0,f;f=E[d++];)f.O&&f.O(a);B=n},fa:b,pe:function(){return B},get:function(a,b){var d=s[a];if(d)return d.H?d.H(h(b)):{}},la:function(a,d){var b=
m[a];if(b){for(var f=[],g=h(d),p=0,s;s=b[p++];)f.push(s.H?s.H(g):{});return f}return[]},Aa:function(){return a},Ca:function(){return i},Ki:function(a,d){var b=m[w.Ze];if(b)for(var f=0,g;g=b[f++];)if(g.M()==a)return g.H?g.H(h(d)):{};return o}};(function(){if(d.Yc){var a=v.nh(),b,p,h,m;for(m in a){var e=m;b=a[e];p=q[e];if(h=c[e]){if(h!=f.ff&&p&&h.length){p=c;h=h.slice(0);for(var j=[],z={},i=0,V=ca,O=ca;O=h[i++];)O instanceof Object&&(V=O.M(),z[V]||(j.push(O),z[V]=1),h.splice(--i,1));i=la(h);i[f.yf]&&
(i=la(h.concat(b)),delete i[f.yf]);for(V in i)z[V]||j.push(parseInt(V,10));p[e]=j}}else c[e]=p?b:b[0]}}k(c);for(a=0;m=r[a++];)c[m]||(p=l(m,ca))&&(s[m]=p);k(t);E.sort(g);for(a=0;m=E[a++];)m.W&&m.W(D);for(a=0;m=E[a++];)m.X&&m.X(d);B=n})();return D},Wb=function(a,c,j){function e(){return a}function i(){return p}function d(){return s}function b(){return c}function k(){return j||""}function l(){return E}function h(a,b){q(a,b)}function g(a,b){q(a,b,n)}function f(){B||(v=D=n)}function q(a,b,d){B||(v=n,m[a]=
b,d&&(t[a]=b))}var r=Ea(),p,s,m={},t={},z,E,B=u,v=u,D=u,y=u,J={oa:function(){return r},ia:e,Af:i,qa:d,Xa:b,Ub:function(){return m},Cf:function(){return z},ri:k,Pd:l,be:function(){return{ia:e,Af:i,qa:d,Xa:b,ri:k,Pd:l,setParameter:h,Qd:g,qi:f}},setParameter:h,Qd:g,qi:f,hh:function(){return D},gh:function(){v=y=n},sg:function(b,d,f){return!v&&a==b&&c.pi(d)&&j==f},Fe:function(){return y},fh:function(){B||(E=sa(),"cp"in t||g("cp",c.gb()),q("gs_id",r),z=Ca(t)+":"+s,v=B=n)}};p=a.toLowerCase();s=Da(p);return J},
Xb=function(a,c,j,e,i,d,b,k){function l(){return c}function h(){return j}function g(){return!!j&&!!j[0]}var f=n,q,r={za:function(){return a},ia:l,ee:function(){return g()?j[0]:o},ha:h,Ba:g,gj:function(a){return!!e[a]},Fd:function(a){return a in e?e[a]:0},Zh:function(a){return a in e?e[a]:""},mh:function(a){return a in e?e[a]:o},Sd:function(){var a={},b;for(b in e)a[b]=e[b];return a},Ae:function(){return i},qc:function(){return d},Uh:function(){return b},Ye:function(){return k},Be:function(){b=n},
B:function(){return f},We:function(){q||(q={ia:l,ha:h});return q}};j?j.length&&33==j[0].B()&&(d=f=u):j=[];return r},Yb=function(a,c,j,e,i,d){function b(a){if(i)for(var b=0,d;d=a[b++];)if(-1!=Ba(d,i))return n;return u}var k=u,l={vb:function(){return a},Y:function(){return c},Ta:function(){return j},B:function(){return e},Ua:function(){return i||[]},oi:function(a){return!!i&&b([a])},ni:b,Ga:function(){return d||[]},Wc:function(){return k}};switch(e){case 0:case 38:case 39:case 400:case 35:case 33:case 41:case 34:case 44:case 45:case 40:k=
n}return l};
(function(){var a=/\s/g,c=/\u3000/g,j=/^\s/,e=/\s+/,i=/\s+/g,d=/^\s+|\s+$/g,b=/^\s+$/,k=/<[^>]*>/g,l=/&nbsp;/g,h=/&#x3000;/g,g=[/&/g,/&amp;/g,/</g,/&lt;/g,/>/g,/&gt;/g,/"/g,/&quot;/g,/'/g,/&#39;/g,/{/g,/&#123;/g],f=document.getElementsByTagName("head")[0],q=0;Ha=function(a,b){b===ca&&(b=a);var d=function(){return b};return{gb:d,ti:function(){return a},si:d,ij:function(){return a<b},pi:function(d){return d&&a==d.ti()&&b==d.si()}}};Ga=function(a,b,d,f){if(b==o||""===b){if(!f)return;b=""}d.push(a+"="+
encodeURIComponent(""+b))};Ca=function(a){var b=[],d;for(d in a)Ga(d,a[d],b);return b.join("&")};Ia=function(a){return!!a&&!b.test(a)};Ja=function(a){for(var b=g.length,d=0;d<b;d+=2)a=a.replace(g[d],g[d+1].source);return a};Ka=function(a){for(var b=g.length,d=0;d<b;d+=2)a=a.replace(g[d+1],g[d].source);a=a.replace(l," ");return a.replace(h,"\u3000")};La=function(a){return a.replace(Tb,"")};Ma=function(a){return a.replace(k,"")};Oa=function(b){return b&&(-1<b.indexOf(" ")||e.test(b))?(b=b.replace(c,
"&#x3000;"),b.replace(a,"&nbsp;")):b};Da=function(a,b){return a&&(-1<a.indexOf(" ")||e.test(a))?(a=a.replace(i," "),a.replace(b?d:j,"")):a};Pa=function(a,b,d){d&&(a=a.toLowerCase(),b=b.toLowerCase());return b.length<=a.length&&a.substring(0,b.length)==b};Qa=function(a){window.clearTimeout(a)};Aa=function(){};Ra=function(){return f};Ea=function(){return(q++).toString(36)};Sa=function(a){return Kb.test(a)};Ba=function(a,b){if(b.indexOf)return b.indexOf(a);for(var d=0,f=b.length;d<f;++d)if(b[d]===a)return d;
return-1};Ta=function(a,b){return a.Ha()-b.Ha()}})();
(function(){function a(a,b){var c=document.createElement(a);b&&(c.className=b);return c}function c(d){return a("div",d)}function j(a,b){var c=a.getElementsByTagName("input");if(c)for(var e=0,h;h=c[e++];)if(h.name==b&&"submit"!=h.type.toLowerCase())return h;return o}function e(a){a&&(a.preventDefault&&a.preventDefault(),a.returnValue=u);return u}function i(a){return a.ownerDocument||a.document}ab=function(a,b){if(a.setSelectionRange)a.setSelectionRange(b,b);else{var c=i(a).selection;c&&c.createRange&&
(c=c.createRange(),c.collapse(n),c.moveEnd("character",b),c.moveStart("character",b),c.select())}};bb=function(a){try{var b,c;if("selectionStart"in a)b=a.selectionStart,c=a.selectionEnd;else{var e=a.createTextRange(),h=i(a).selection.createRange();e.inRange(h)&&(e.setEndPoint("EndToStart",h),b=e.text.length,e.setEndPoint("EndToEnd",h),c=e.text.length)}if(b!==ca)return Ha(b,c)}catch(g){}return o};cb=function(a,b){for(var c=0,e=0;a&&!(b&&a==b);){c+=a.offsetTop;e+=a.offsetLeft;try{a=a.offsetParent}catch(h){a=
o}}return{Qh:c,Ph:e}};db=function(a){return i(a).activeElement==a};eb=function(a){return 38==a||40==a};Ya=a;fb=function(){var d=a("table");d.cellPadding=d.cellSpacing=0;d.style.width="100%";return d};gb=c;hb=function(a,b){var e=c(a),j=e.style;j.background="transparent";j.color="#000";j.padding=0;j.position="absolute";j.top="1px";b&&(j.zIndex=b);j.whiteSpace="pre";return e};ib=function(a,b){a.innerHTML!=b&&(b&&(Wa?b=Oa(b):Xa&&(b=['<pre style="font:inherit;margin:0">',b,"</pre>"].join(""))),a.innerHTML=
b)};jb=function(a,b){if(a.dir!=b){var c=a.style;c.left=c.right="";c["rtl"==b?"right":"left"]="1px";a.dir=b}};kb=function(d,b,c){if(j(d,b))return o;var e=a("input");e.type="hidden";e.name=b;c&&(e.value=c);return d.appendChild(e)};lb=j;mb=function(a){var b=document.createEvent("KeyboardEvent");b.initKeyEvent("keypress",n,n,o,u,u,n,u,27,0);a.dispatchEvent(b)};qb=e;rb=function(a){if(a=a||window.event)a.stopPropagation&&a.stopPropagation(),a.cancelBubble=a.cancel=n;return e(a)};sb=function(a,b){b.parentNode.insertBefore(a,
b.nextSibling)};tb=function(a){var a=a.insertCell(-1),b=Ya("a");b.href="#ifl";b.className="gssb_j gss_ifl";a.appendChild(b);return b};ub=function(a,b){var c=window.getComputedStyle?window.getComputedStyle(a,""):a.currentStyle;return c?c[b]:o};vb=function(){var a=window.innerWidth,b=window.innerHeight;if(!a){var c=document.documentElement;c&&(a=c.clientWidth,b=c.clientHeight);a||(a=document.body.clientWidth,b=document.body.clientHeight)}return{Ef:a,Df:b}};wb=function(a){a=a.style;a.border="none";a.padding=
Za||$a?"0 1px":"0";a.margin="0";a.height="auto";a.width="100%"};xb=function(a){var b={};if(a)for(var c=0,e;e=a[c++];)b[e.wb()]=e;return b};yb=i})();
K.Pf(150,95,function(){function a(a,j){j=Ja(La(j));a=Ja(Da(a,n));if(Pa(j,a))return[a,"<b>",j.substr(a.length),"</b>"].join("");for(var e=[],i=[],d=j.length-1,b=0,k=-1,l;l=j.charAt(b);++b)" "==l||"\t"==l?e.length&&(i.push({t:e.join(""),xb:k,e:b+1}),e=[],k=-1):(e.push(l),-1==k?k=b:b==d&&i.push({t:e.join(""),xb:k,e:b+1}));e=a.split(/\s+/);b={};for(d=0;k=e[d++];)b[k]=1;l=-1;for(var e=[],h=i.length-1,d=0;k=i[d];++d)b[k.t]?(k=-1==l,d==h?e.push({xb:k?d:l,e:d}):k&&(l=d)):-1<l&&(e.push({xb:l,e:d-1}),l=-1);
if(!e.length)return["<b>",j,"</b>"].join("");d=[];for(b=k=0;l=e[b];++b)(h=i[l.xb].xb)&&d.push("<b>",j.substring(k,h-1),"</b> "),k=i[l.e].e,d.push(j.substring(h,k));k<j.length&&d.push("<b>",j.substring(k),"</b> ");return d.join("")}return{B:function(){return 150},M:function(){return 95},H:function(){return{bold:a}}}});
K.register(146,12,function(){function a(a){a=c(a,f,j);a=c(a,q,e);return c(a,p,i)}function c(a,b,f){for(var d,g,c=0;(d=b.exec(a))!=o;)g||(g=[]),c<d.index&&g.push(a.substring(c,d.index)),g.push(f(d[0])),c=b.lastIndex;if(!g)return a;c<a.length&&g.push(a.substring(c));return g.join("")}function j(a){return String.fromCharCode(a.charCodeAt(0)-65248)}function e(a){var d=a.charCodeAt(0);return 1==a.length?b.charAt(d-65377):65438==a.charCodeAt(1)?k.charAt(d-65395):l.charAt(d-65418)}function i(a){var b=a.charCodeAt(0);
return 12443==a.charCodeAt(1)?h.charAt(b-12454):g.charAt(b-12495)}function d(a){return eval('"\\u30'+a.split(",").join("\\u30")+'"')}var b=d("02,0C,0D,01,FB,F2,A1,A3,A5,A7,A9,E3,E5,E7,C3,FC,A2,A4,A6,A8,AA,AB,AD,AF,B1,B3,B5,B7,B9,BB,BD,BF,C1,C4,C6,C8,CA,CB,CC,CD,CE,CF,D2,D5,D8,DB,DE,DF,E0,E1,E2,E4,E6,E8,E9,EA,EB,EC,ED,EF,F3,9B,9C"),k=d("F4__,AC,AE,B0,B2,B4,B6,B8,BA,BC,BE,C0,C2,C5,C7,C9_____,D0,D3,D6,D9,DC"),l=d("D1,D4,D7,DA,DD"),h=d("F4____,AC_,AE_,B0_,B2_,B4_,B6_,B8_,BA_,BC_,BE_,C0_,C2__,C5_,C7_,C9______,D0__,D3__,D6__,D9__,DC"),
g=d("D1__,D4__,D7__,DA__,DD"),f=/[\uFF01-\uFF5E]/g,q=RegExp("([\uff73\uff76-\uff84\uff8a-\uff8e]\uff9e)|([\uff8a-\uff8e]\uff9f)|([\uff61-\uff9f])","g"),r="(["+d("A6,AB,AD,AF,B1,B3,B5,B7,B9,BB,BD,BF,C1,C4,C6,C8,CF,D2,D5,D8,DB")+"]\u309b)|(["+d("CF,D2,D5,D8,DB")+"]\u309c)",p=RegExp(r,"g");return{B:function(){return 146},M:function(){return 12},H:function(){return{hj:a}}}});
var Zb=function(a,c){var j=zb?"-moz-":$a?"-ms-":Za?"-o-":Ab?"-webkit-":"",e=document.body.style.opacity!=ca,i=[];return{addRule:function(a,b){c&&i.push(a,"{",b,"}")},Wh:function(){if(c&&i.length){c=u;var d=Ya("style");d.setAttribute("type","text/css");(a||Ra()).appendChild(d);var b=i.join("");i=o;d.styleSheet?d.styleSheet.cssText=b:d.appendChild(document.createTextNode(b))}},jj:function(a){return e?"opacity:"+a+";":["filter:",Wa?"progid:DXImageTransform.Microsoft.Alpha(":"alpha(","opacity=",Math.floor(100*
a),");"].join("")},prefix:function(a,b){var c=[a,b||""];j&&(c=c.concat(b?[a,j,b]:[j,a]));return c.join("")}}};
K.register(147,10,function(){function a(a){var f=0;a&&(b||j(),e(),a in k?f=k[a]:(ib(b,Ja(a)),k[a]=f=b.offsetWidth,ib(b,"")));return f}function c(){b||j();e();l||(ib(b,"|"),l=b.offsetHeight);return l}function j(){b=hb(i.Da);b.style.visibility="hidden";d.appendChild(b)}function e(){var a=ub(b,"fontSize");if(!h||a!=h)k={},l=o,h=a}var i,d,b,k,l,h;return{ga:function(a){d=a.xe()||document.body},X:function(a){i=a},B:function(){return 147},M:function(){return 10},H:function(){return{getWidth:a,getHeight:c}}}});
var $b=function(a){var c;(function(){var j=function(){};a||(a={});var e=function(c){return a[c]||j};c={Td:e("a"),search:e("b"),tc:e("c"),tb:e("d"),ub:e("e"),hc:e("f"),yd:e("g"),zd:e("h"),vd:e("i"),Wd:e("j"),lc:e("k"),Jd:e("l"),xd:e("m"),vc:e("n"),Bd:e("o"),Cd:e("p"),rc:e("q"),Ud:e("r"),Nf:e("s"),Of:e("t"),wd:e("u"),Mf:e("v"),Dd:e("w"),sd:e("x"),ud:e("z"),td:e("aa")}})();return{Td:function(){return c.Td()},search:function(a,e){c.search(a,e)},tc:function(a){c.tc(a)},tb:function(a){c.tb(a)},ub:function(a){return c.ub(a)},
hc:function(a){c.hc(a)},yd:function(a){c.yd(a)},zd:function(a){c.zd(a)},vd:function(a){c.vd(a)},Wd:function(a,e){c.Wd(a,e)},lc:function(a,e){c.lc(a,e)},Jd:function(){c.Jd()},xd:function(a){c.xd(a)},vc:function(a){c.vc(a)},Bd:function(){c.Bd()},Cd:function(){c.Cd()},rc:function(a){c.rc(a)},Ud:function(a,e){c.Ud(a,e)},Nf:function(a){c.Nf(a)},Of:function(){c.Of()},wd:function(){c.wd()},Mf:function(){c.Mf()},Dd:function(a){c.Dd(a)},sd:function(){c.sd()},ud:function(){c.ud()},td:function(){c.td()}}};
K.register(149,6,function(){function a(a){m=a;0==a.xa&&(a=h.zf(),f=a.protocol,q=a.host,r=a.Ra,p=a.Bf,s="https:"==document.location.protocol,k(b),(new Image).src=f+q+"/generate_204")}function c(a,b,c,h){var e=a.oa(),E=a.ia();m.ob||d();var b=[f,q,r,"?",p?p+"&":"",b?b+"&":""].join(""),i=Ga,a=[];i("q",E,a,n);m.mb||i("callback","google.sbox.p"+g,a);if(s){for(var E=[],j=4+Math.floor(32*Math.random()),k=0,P;k<j;++k)P=0.3>Math.random()?48+Math.floor(10*Math.random()):(0.5<Math.random()?65:97)+Math.floor(26*
Math.random()),E.push(String.fromCharCode(P));i("gs_gbg",E.join(""),a)}i=Ya("script");i.src=b+a.join("&");t[e]=i;z=m.ob?h:c;l.appendChild(i);return n}function j(){return 0}function e(){return 0}function i(a){var b=t[a];b&&(l.removeChild(b),delete t[a])}function d(){for(var a in t)l.removeChild(t[a]);t={};z=o}function b(a){z&&z(a,u)}function k(a){a||(a=Aa);var b=window.google;m.mb?b.ac.h=a:b.sbox["p"+g]=a}var l=Ra(),h,g,f,q,r,p,s,m,t={},z,E={W:function(a){h=a.get(127,E);g=a.Ca().oa()},X:a,O:a,B:function(){return 149},
M:function(){return 6},H:function(){return{Ee:c,De:i,ib:Aa,Vd:j,Od:e}},fa:function(){k(o);d()}};return E});
K.register(145,1,function(){function a(a){if(!k)return n;for(var b=u,f=u,d=0,c;d<a.length;++d)if(c=a.charAt(d),!e.test(c)&&(i.test(c)?f=n:b=n,f&&b))return n;return u}function c(a,c,f){if(!k)return n;var i=d.test(f),j=b.test(c);return"ltr"==a?i||j||e.test(f)||e.test(c):!i||!j}function j(a){var b=l;k&&(i.test(a)?b="ltr":e.test(a)||(b="rtl"));return b}var e=RegExp("^[\x00- !-@[-`{-\u00bf\u00d7\u00f7\u02b9-\u02ff\u2000-\u2bff]*$"),i=RegExp("^[\x00- !-@[-`{-\u00bf\u00d7\u00f7\u02b9-\u02ff\u2000-\u2bff]*(?:\\d[\x00- !-@[-`{-\u00bf\u00d7\u00f7\u02b9-\u02ff\u2000-\u2bff]*$|[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u2c00-\ufb1c\ufdfe-\ufe6f\ufefd-\uffff])"),
d=RegExp("^[\x00- !-@[-`{-\u00bf\u00d7\u00f7\u02b9-\u02ff\u2000-\u2bff]*(?:\\d|[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u2c00-\ufb1c\ufdfe-\ufe6f\ufefd-\uffff])"),b=RegExp("(?:\\d|[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u2c00-\ufb1c\ufdfe-\ufe6f\ufefd-\uffff])[\x00- !-@[-`{-\u00bf\u00d7\u00f7\u02b9-\u02ff\u2000-\u2bff]*$"),k=i.test("x"),l;return{ga:function(a){l=a.Jc()},B:function(){return 145},M:function(){return 1},H:function(){return{fj:a,
wg:c,Ob:j}}}});
K.register(117,2,function(){function a(a,b,f,d,c){var e=g(a);e||(e={},p.push({element:a,ji:e}));var m=e[b];m||(m=e[b]=[],e=h(b,m),"string"!=typeof b?a[b]=e:a.addEventListener?a.addEventListener(b,e,u):a["on"+b]=e);a={Yd:f,Lf:d||0};c&&(a.li=n);m.push(a);m.sort(q);f.ii=b}function c(a,b){var f=g(a);if(f&&(f=f[b.ii]))for(var d=0,c;c=f[d++];)if(c.Yd==b){c.Kf=n;break}}function j(b,f,d,c){a(s,b,f,d,c)}function e(a){c(s,a)}function i(a,b){var f=b||{},d=s[a];d&&d(f,f.hb)}function d(a,b,f){a.addEventListener?a.addEventListener(b,
f,u):a.attachEvent("on"+b,f)}function b(a,b,f){a.removeEventListener?a.removeEventListener(b,f,u):a.detachEvent("on"+b,f)}function k(a){r?(m||(m=[],d(window,"message",l)),m.push(a),a=window.location.href,window.postMessage("sbox.df",/HTTPS?:\/\//i.test(a)?a:"*")):window.setTimeout(a,0)}function l(a){m&&a&&a.source==window&&"sbox.df"==a.data&&m.length&&(m.shift()(),m&&m.length&&window.postMessage("sbox.df",window.location.href))}function h(a,b){return function(d,c){if(b.length){var g;if(!(g=d)){g=
{};var h=window.event;h&&(h.keyCode&&(g.keyCode=h.keyCode),g.ki=n)}g.hb=c||a;for(var h=g,e,p,m=0,i;i=b[m++];)i.Kf?p=n:e||(i.li?f(i,h):e=i.Yd(h));if(p)for(m=0;i=b[m];)i.Kf?b.splice(m,1):++m;if(g.nc)return delete g.nc,g.ki&&(g=window.event||g),rb(g),g.returnValue=u}}}function g(a){for(var b=0,f;b<p.length;++b)if(f=p[b],f.element==a)return f.ji;return o}function f(a,b){k(function(){a.Yd(b)})}function q(a,b){return b.Lf-a.Lf}var r=window.postMessage&&!($a||Bb||Za),p=[],s={},m;return{B:function(){return 117},
M:function(){return 2},H:function(){return{ka:a,Cg:c,jc:j,ej:e,Z:i,listen:d,unlisten:b,defer:k}},fa:function(){m=o}}});
K.register(118,3,function(){function a(a){Pb=Fa.Za();va=a;Q(G.Sf());nb=Ua=u}function c(){var a={};T.Z(14,a);!a.cancel&&va.yb&&H.Gc()}function j(){T.Z(13);ka.wd()}function e(){aa("rtl")}function i(){aa("ltr")}function d(a){H.Ba()?H.Qf():H.Bb(a)}function b(){if(0==va.Va)return u;var a=oa();if(a)switch(va.Va){case 1:return ga(a,n)}return u}function k(){va.Dc?W(5):(H.Wa()?H.Gc():s(),D())}function l(a){Z&&a.gb()==Z.length&&(T.Z(9),va.Cc&&W(2),ka.vd(Z))}function h(a){R&&0==a.gb()&&R.zg()}function g(a,b,
f,d){va.Ac&&!a&&H.$d(n);va.yc&&!H.Wa()&&"mousedown"==f&&H.Bb(b);var c;Na&&Na.sg(a,b,f)?c=Na:Na=c=Wb(a,b,f);b=d;d=u;if(a!=Z||"onremovechip"==f)Q(a),T.Z(1,{hb:f,Ed:xa}),ka.hc(a),d=sa(),Va||(Va=d),ob=d,Ia(a)&&(b=n),d=n;var a=C.DONT_CARE,g=c.be(),h=ma.Ja();if(ea)for(var e=0,m;m=ea[e++];)m=m.Xc(g,h),m>a&&(a=m);switch(a){case C.xg:b=n;break;case C.yg:b=u}b?(Ua&&c.setParameter("gs_is",1),ka.xd(Ua),H.Rf(),wa.Zd(c),G.focus(),Na=o):d&&(H.clear(),wa.xc());T.Z(2,{hb:f})}function f(a){Ua=a}function q(a){nb!=a&&
((nb=a)?ka.ud():ka.td())}function r(a){fa(a)}function p(){G.focus()}function s(){G.blur()}function m(){return G.Ec()}function t(a,b){Pa(a,Z,n)&&(a=Z+a.substr(Z.length));var f=Ha(a.length);g(a,f,"",b);fa(a,n)}function z(a){t(a,n);pb=sa()}function E(){g(Z,N(),"onremovechip")}function B(a){Q(a);G.refresh();T.Z(4,{Ed:xa,input:a})}function v(){G.select()}function D(){Z!=ya&&Q(ya);T.Z(5,{input:ya,ug:H.ha(),Ed:xa});G.refresh();ka.zd(ya)}function y(){ya=Z}function J(){return G.je()}function L(){return ya}
function A(){return Z}function M(){return xa}function N(){return G.Xa()}function P(){return G.Vc()}function ha(){return G.getHeight()}function da(){return G.getWidth()}function V(){return Va}function O(){return ob}function U(){return pb}function I(){return 0!=Pb}function Y(){for(var a=0,b;b=Qb[a++];)if(b.isEnabled())return n;return u}function F(a){var b=Z.length,f=a.substr(0,b),a=a.substr(b);return!!a&&f==Z&&$.wg(xa,Z,a)}function S(){G.Hc()}function W(a){ba.search(Z,a)}function x(a){Z&&(Z=ya="",G.clear(),
T.Z(1),H.clear(),ka.hc(Z),a&&ka.sd())}function X(){pb=ob=Va=0}function na(a){G.me(a)}function ia(){var a=oa();a&&ga(a)}function aa(a){var f=N().gb();xa==a?H.Ba()&&f==Z.length&&(H.Ma()?va.Ab&&(a=H.Ia(),ba.search(a.Y(),6)):va.Bc&&b()):R&&0==f&&R.zg()}function oa(){if(H.Ba()){var a=H.Ma()?H.Ia():H.ee();if(a.Wc())return a}return o}function ga(a,b){var f=a.Y();return ya!=f?(y(),b?t(f,n):B(f),n):u}function fa(a,b){Z=a||"";ja();G.refresh();b||(T.Z(4,{Ed:xa,input:Z}),ka.yd(Z))}function ja(){var a=$.Ob(Z);
a!=xa&&(G.va(a),xa=a)}function Q(a){Z=ya=a||"";ja()}var C=Nb,G,H,R,T,ba,ma,$,ea,Fa,ka,wa,Qb,ya,Z,xa,Pb,Va,ob,pb,Ua,nb,Na,va,qa={W:function(a){R=a.get(130,qa);$=a.get(145,qa);T=a.get(117,qa);wa=a.get(123,qa);ba=a.get(121,qa);ea=a.la(156,qa);ma=a.get(126,qa);a.get(127,qa);H=a.get(128,qa);G=a.get(119,qa);Qb=a.la(160,qa);Fa=a.Ca();ka=a.Aa()},X:function(b){ea.sort(Ta);a(b)},O:a,B:function(){return 118},M:function(){return 3},H:function(){return{ke:c,Xf:j,Zf:e,$f:i,Vf:d,eg:b,Wf:k,Uf:l,Tf:h,Yf:g,gg:f,le:q,
$a:r,vg:p,Pb:s,yi:m,he:t,ui:z,vi:E,Fc:B,ge:v,ie:D,tg:y,je:J,ra:L,ma:A,Ob:M,Xa:N,Vc:P,getHeight:ha,getWidth:da,pg:V,qg:O,rg:U,fg:I,ed:Y,wi:F,Hc:S,search:W,clear:x,Oa:X,me:na,fe:ia}}};return qa});
K.register(120,9,function(){function a(a){p=a;j()}function c(a){var b=h.ra(),c="f";f.oc()?c="o":g.Ma()&&(c=za(g.Ia()));var m="";a!=ca&&(m=a+"");a="";f.oc()?a="o":g.Ma()&&(a=g.ve());var m=[[p.Fa?p.Fa.replace(l,"-"):"",m,a,d(),i().replace(l,"j"),p.Qa?p.Qa.replace(l,"-"):"",e()].join(".").replace(k,""),""].join("."),s="";if(a=g.ha()){for(var s={Xd:[],uc:o,count:0},j=a.length,t=0,q;t<j;++t){q=t==j-1;var A=a[t],M=s,N=r[A.B()].sb();(A=ua(A.Ua()))&&(N+="-"+A);N!=M.uc&&(M.count&&M.Xd.push(M.uc,M.count),M.count=
0,M.uc=N);++M.count;q&&M.count&&M.Xd.push(M.uc,M.count)}s=s.Xd.join("")}return{oq:b,aq:c,aqi:s,aql:e(),gs_l:m}}function j(){m=sa();++s;h.Oa();q.Oa()}function e(){var a="",b=f.Ja();b&&(a=b.mh("e")?"1":"");return a}function i(){var a=sa()-m;return[b(h.pg()),b(h.qg()),s,a,q.Ng(),q.Mg(),q.Gd(),q.Hd(),q.Jg(),q.Lg(),q.Kg(),q.Pg(),q.Ig(),q.Og(),b(h.rg())].join("l")}function d(){var a="",b=g.ha();if(b){for(var f,d=0,c=0,h;h=b[c++];){var e=h;h=e.B()+"";e=e.Ua();e.length&&(h+="i"+e.join("i"));h!=f&&(1<d&&(a+=
"l"+d),a+=(f?"j":"")+h,d=0,f=h);++d}1<d&&(a+="l"+d)}return a}function b(a){return Math.max(a-m,0)}var k=/\.+$/,l=/\./g,h,g,f,q,r,p,s=-1,m,t={W:function(a){h=a.get(118,t);g=a.get(128,t);f=a.get(126,t);q=a.get(123,t);r=xb(a.la(152,t))},X:a,O:a,B:function(){return 120},M:function(){return 9},H:function(){return{Ub:c,reset:j}}};return t});
K.register(121,11,function(){function a(a){t=a}function c(a,f){if(Ia(a)||t.wa||k&&k.wa())Sa(f)?m&&!s&&(s=kb(m,"btnI","1")):s&&(m.removeChild(s),s=o),p.search(a,f),b(),l.Z(15,{Gg:a})}function j(a){p.tc(a);b()}function e(a){p.tb(a);b()}function i(a){p.rc(a);b()}function d(a){return p.ub(a)}function b(){h.xc();h.Yg();f.reset();q.clear();g.ra()!=g.ma()&&g.tg();r&&r.clear()}var k,l,h,g,f,q,r,p,s,m,t,z={ga:function(a){m=a.xe()},W:function(a){k=a.get(130,z);l=a.get(117,z);h=a.get(123,z);g=a.get(118,z);f=
a.get(120,z);q=a.get(128,z);r=a.get(139,z);p=a.Aa()},X:a,O:a,B:function(){return 121},M:function(){return 11},H:function(){return{search:c,tc:j,tb:e,rc:i,ub:d}}};return z});
K.register(124,14,function(){var a,c,j,e;function i(a){h=a.ua;f=a.jb}function d(a){return(a[l.If]||{}).j}function b(a){return a[l.Hf]}function k(b,d){var m=b[l.Hf],i=b[l.hi],r={},k=b[l.If];if(k)for(var B in k){var v=k[B];B in q&&(v=q[B].parse(v));r[B]=v}var k=Xb,D=u,y=u;B=u;for(var v=0,J;J=i[v++];)if(33==(J[a]||0)?y=n:D=n,y&&D){B=n;break}D=0;y=[];for(v=0;J=i[v++];){var L=J[a]||0;if(h[L]&&(!B||33!=L)){var A;A=J[j];f&&(A=g.bold(m.toLowerCase(),Ma(Ka(A))));y.push(Yb(A,Ma(Ka(A)),D++,L,ta(J[c]),J[e]))}}return k(d,
m,y,r,u,n,u,u)}var l=Ob;j=0;a=1;c=2;e=3;var h,g,f,q={},r={W:function(a){g=a.get(150,r);if(a=a.la(158,r))for(var b=0,f;f=a[b++];)q[f.Ni()]=f},X:i,O:i,B:function(){return 124},M:function(){return 14},H:function(){return{ih:d,Oi:b,Rd:k}}};return r});
K.register(125,15,function(){function a(a){var g=c(a);if(g){i&&!a.Ye()&&(a=i.Li(a));d.Sh(a);var f=a,e=f.za().ia(),r=f.ha();b.isEnabled()&&(r.length?(f=f.B()==u,b.setSuggestions(e,r,f)):b.clear());j.Z(3,{input:e,ug:r})}k.Wd(a,g);return g}function c(a){var b=e.ma(),f=d.Ja(),b=b.toLowerCase(),c=a.ia().toLowerCase();b==c?f=n:(b=Da(b),a=(c=a.za())?c.qa():Da(a.ia().toLowerCase()),f=f?f.za().qa():"",f=0==b.indexOf(a)?0==b.indexOf(f)?a.length>=f.length:n:u);return f}var j,e,i,d,b,k,l={W:function(a){j=a.get(117,
l);e=a.get(118,l);i=a.get(122,l);d=a.get(126,l);b=a.get(128,l);k=a.Aa()},B:function(){return 125},M:function(){return 15},H:function(){return{Ce:a,Xb:c}}};return l});
K.register(123,13,function(){function a(a){da=Y.Wg();ba=a;W={};Q=0;G=a.$c;H=a.Mb;R=u;T=ba.Zc&&!!P;ma=a.Nb}function c(a,b){if(!(H||ha&&ha.Ii())){a.Qd("ds",ba.Lb);a.Qd("pq",ma);a.fh();var f=n;R=u;++x;var c=sa(),g;for(g in W){var e=W[g].Pd();2500<c-e&&J(g)}if(T&&(c=P.get(a)))(f=G||a.hh())&&ba.dd&&a.gh(),U.Ce(c),c.Ae()&&++ia,d();f?(S=a,(!C||b)&&y()):++X}}function j(){return 10<=na||3<=da.Od()?n:u}function e(){R=n}function i(){return R}function d(){S=o}function b(){return x}function k(){return X}function l(){return T?
P.Gd():-1}function h(){return T?P.Hd():-1}function g(){return ia}function f(){return aa}function q(){return oa}function r(){return ga}function p(a){a=O.Rd(a,o);return U.Xb(a)}function s(){return fa}function m(){for(var a=[],b=0,f,d=0;d<=M;++d)f=ja[d],0==f?b++:(b=1==b?"0.":1<b?d+"-":"",a.push(b+f),b=0);return a.join(".")}function t(){T&&P.Zg()}function z(a){T&&P.$g(a)}function E(a,b){return O.Rd(a,b)}function B(){T&&P.Oa();fa=ga=oa=aa=ia=na=X=x=0;ja=[];for(var a=0;a<=M;++a)ja[a]=0}function v(a){ma=
a}function D(a){return function(b,f){L(b,f,a)}}function y(){Qa(C);C=o;if(!(2<da.Od())&&S){var a=[],b=S.Ub();if(b)for(var f in b)Ga(f,b[f],a);F.Jd();a=da.Ee(S,a.join("&"),D(S),L);b=S.Fe();a&&!b&&(a=S,W[a.oa()]=a,++na,++X);d();a=100;b=(na-2)/2;for(f=1;f++<=b;)a*=2;a<Q&&(a=Q);C=window.setTimeout(y,a)}}function J(a){da.De(a);delete W[a];na&&--na}function L(a,b,f){++aa;if(!f&&(f=O.ih(a),f=W[f],!f))return;if(!f.Fe()){a=O.Rd(a,f);if(I)var d=V.ma(),a=I.Ji(a,d);b&&a.Be();T&&P.put(a);R||(U.Ce(a)||++oa,b=f,
Q=a.Fd("d"),b&&(J(b.oa()),b=b.Pd(),b=sa()-b,fa+=b,ga=Math.max(b,ga),++ja[b>N?M:A[Math.floor(b/100)]]))}}var A=[0,1,2,3,4,5,5,6,6,6,7,7,7,7,7,8,8,8,8,8],M=A[A.length-1]+1,N=100*A.length-1,P,ha,da,V,O,U,I,Y,F,S,W,x,X,na,ia,aa,oa,ga,fa,ja,Q,C,G,H,R,T,ba,ma,$={W:function(a){P=a.get(133,$);ha=a.get(130,$);a.get(117,$);V=a.get(118,$);O=a.get(124,$);U=a.get(125,$);I=a.get(230,$);a.get(126,$);Y=a.get(127,$);a.get(128,$);F=a.Aa()},X:a,O:a,B:function(){return 123},M:function(){return 13},H:function(){return{Zd:c,
oc:j,xc:e,re:i,Yg:d,Ng:b,Mg:k,Gd:l,Hd:h,Jg:g,Og:f,Lg:q,Kg:r,Xb:p,Pg:s,Ig:m,ib:t,eh:z,se:E,Oa:B,ue:v}},fa:function(){Qa(C);C=o;d();W=o;R=n}};return $});K.register(126,5,function(){function a(){h=l=0;i()}function c(){return d.oc()}function j(a){k=a;++l;a.Uh()&&++h;b.vc&&b.vc(h/l)}function e(){return k}function i(){k=o}var d,b,k,l,h,g={W:function(a){d=a.get(123,g);b=a.Aa()},X:a,O:a,B:function(){return 126},M:function(){return 5},H:function(){return{oc:c,Sh:j,Ja:e,Pi:i}}};return g});
K.register(127,16,function(){function a(a){var c="https:"==document.location.protocol||a.nb,g=Ga,f=[];g("client",a.Fa,f);g("hl",a.Ka,f);g("gl",a.dc,f);g("sugexp",a.Qa,f);g("gs_nf",1,f);a.authuser&&g("authuser",a.authuser,f);b={protocol:"http"+(c?"s":"")+"://",host:a.qd||"clients1."+a.$b,Ra:a.Ra||"/complete/search",Bf:f.length?f.join("&"):""};if(!d||d.Vd()!=a.xa)d=i[a.xa]}function c(){return d}function j(){return b}function e(){d&&d.ib()}var i={},d,b,k={W:function(a){for(var a=a.la(149,k),b=0,d;d=
a[b++];)i[d.Vd()]=d},X:a,O:a,B:function(){return 127},M:function(){return 16},H:function(a){return{Wg:123==a?c:Aa,zf:j,Rh:e}}};return k});
K.register(128,17,function(){function a(a){$=a;G=C=o;H=Y.EMPTY;R=u;T=n}function c(a,b,f){a=ga&&ga.Ei(b);v();if((Q=b)&&b.length){var d=b[0].Y(),d=S.Ob(d),c=u;f?(H=Y.Eg,c=F.mg(b,d),b=b[0].Ga()[0],b=Ka(b),W.kc(na.getWidth(b))):(H=Y.we,c=F.$(da(),d),W.kc(0));a&&(G=ga.Di(),j(ga.Bi()));W.va(d);c?E():v()}}function j(a){I();if(C!=a){var b=C;C=a;U(b)}}function e(){if(m())if(R){var a=C;C==Q.length-1?G=C=o:C==o?C=0:++C;G=C;O(a,e)}else E()}function i(){if(m())if(R){var a=C;!Q||0==C?G=C=o:C==o?C=Q.length-1:--C;
G=C;O(a,i)}else E()}function d(a){var b=a?4:3;t()?(a=p(),F.Eb(a)||X.search(b),b=X.ra(),ja.lc(b,a)):X.search(b)}function b(a){G=C=a;var a=Q[a],b=X.ra();ja.lc(b,a)}function k(){return R}function l(){return T}function h(a){T&&!a&&v();T=a}function g(){return H}function f(){return Q}function q(){return m()?Q[0]:o}function r(){return C}function p(){return t()?Q[G]:o}function s(){return G}function m(){return!(!Q||!Q.length)}function t(){return G!=o}function z(){R&&!ba&&(ba=window.setTimeout(v,$.Ic))}function E(){R||
(W.Ad(17),W.show(),R=n,ja.Bd())}function B(){R&&(ba&&(Qa(ba),ba=o),W.Sa(),R=u,ja.Cd())}function v(){B();Q=o;H=Y.EMPTY;C!=o&&F.ec(C);G=C=o;F.clear()}function D(){x.xc();B()}function y(){C!=o&&F.ec(C);G=C=o}function J(){I();ma=window.setTimeout(y,0)}function L(){I()}function A(a){if(m())E();else{var b=X.ra();if(b){a=a||X.Xa();b=Wb(b,a);if(aa)for(var a=b.be(),f=oa.Ja(),d=0,c;c=aa[d++];)c.Xc(a,f);x.Zd(b)}}}function M(){return F.ja()}function N(){return F.fd()}function P(){F.Vb()}function ha(){return 17}
function da(){if(m()&&H==Y.we){for(var a=[],b=[],f=0,d;(d=ia[f++])&&!d.Ci(X.ra(),Q,b););(f=b?b.length:0)&&(f-=V(b,a,0));for(d=0;d<Q.length;++d)a.push(Q[d]);f&&(f-=V(b,a,1));$.Na&&a.push(1);f&&V(b,a,2);$.La&&a.push(2);fa&&fa.Ai(a);return a}return o}function V(a,b,f){for(var d=0,c=0,g;c<a.length;++c)if((g=a[c])&&g.position==f)b.push(g),++d;return d}function O(a,b){if(C!=o&&!F.ya(C))F.ec(a),b();else if(U(a),C==o)X.ie();else{var f=F.Zb(Q[C]);X.$a(f);ja.Dd(f)}}function U(a){I();a!=o&&F.ec(a);C!=o&&F.lg(C)}
function I(){ma&&(Qa(ma),ma=o)}var Y=Lb,F,S,W,x,X,na,ia,aa,oa,ga,fa,ja,Q,C,G,H,R,T,ba,ma,$,ea={W:function(a){F=a.get(129,ea);S=a.get(145,ea);W=a.get(115,ea);x=a.get(123,ea);X=a.get(118,ea);na=a.get(147,ea);ia=a.la(153,ea);aa=a.la(156,ea);oa=a.get(126,ea);ga=a.get(184,ea);fa=a.get(157,ea);ja=a.Aa()},X:function(b){aa.sort(Ta);a(b)},O:a,B:function(){return 128},M:function(){return 17},H:function(){return{setSuggestions:c,og:j,Qf:e,hg:i,Eb:d,kg:b,Wa:k,isEnabled:l,$d:h,ig:g,ha:f,ee:q,Ag:r,Ia:p,ve:s,Ba:m,
Ma:t,Rf:z,show:E,Sa:B,clear:v,Gc:D,Bg:y,ng:J,zi:L,Bb:A}},pd:function(){var a={ja:M,fd:N,Vb:P,Dg:ha};return[{ga:Aa,W:Aa,X:Aa,O:Aa,B:function(){return 154},M:function(){return 17},H:function(){return a},pd:Aa,fa:Aa}]},fa:function(){ba&&(Qa(ba),ba=o);Q=o;B()}};return ea});
K.register(115,7,function(){function a(){g=u}function c(a){h.ic(a)}function j(){return g}function e(a){a in f&&a!=q&&(l(),h.Ad(f[a]),q=a)}function i(){return g?h.getHeight():0}function d(a){h.kc(a)}function b(a){h.va(a)}function k(){g||(h.show(),g=n)}function l(){g&&(h.Sa(),g=u)}var h,g,f={},q,r={W:function(a){h=a.get(116,r);a.Aa();if(a=a.la(154,r))for(var b=0,d;d=a[b++];)f[d.Dg()]=d},X:a,O:a,B:function(){return 115},M:function(){return 7},H:function(){return{Wa:j,Ad:e,getHeight:i,kc:d,va:b,show:k,
Sa:l,ic:c}},fa:function(){l()}};return r});
K.register(119,4,function(){function a(a){ia=a;x.setAttribute("autocomplete","off");x.setAttribute("spellcheck",a.spellcheck);x.style.outline=a.Nc?"":"none";oa&&N()}function c(a,b){b||(b=a);x.parentNode.replaceChild(a,x);b.appendChild(x);aa&&ia.Pc&&(x.focus(),($a||zb)&&F.defer(function(){ab(x,fa.gb())}))}function j(){return H}function e(a){var b="rtl"==a,f=b==("rtl"==ea);x.dir=a;if(R){S.va(a);var d=C.parentNode;d.removeChild(R);f?sb(R,C):d.insertBefore(R,C)}H&&(H.dir=a,a=H.parentNode,a.removeChild(H),
f?a.insertBefore(H,C):sb(H,C));0!=X&&(f=x.style,b?(f.left="",f.right="0"):(f.left="0",f.right=""))}function i(){return fa}function d(){return cb(G)}function b(){var a=G?G.offsetHeight:0;ka>a&&(a=ka);return a}function k(){return G?G.offsetWidth:0}function l(){var a=x.offsetWidth;ia.zb&&(a-=x.offsetHeight);return a}function h(){return x.value}function g(a){x.style.background=a||"transparent"}function f(){Q=n}function q(){x.select();V()}function r(){Cb&&(x.value="");x.value=I.ma();Cb&&(x.value=x.value);
E()}function p(){if(!aa)try{x.focus(),aa=n,E()}catch(a){}}function s(){aa&&(x.blur(),aa=u)}function m(){return aa}function t(){x.value=""}function z(){var a=Fa.get("gs_id");if(a)H=Fa.get("gs_ttc"),C=Fa.get("gs_tti"),I.ed()&&S&&(T=S.ja(),R=T.parentNode);else{a=fb();a.className="gstl_"+na+" "+(ia.Db||x.className);var b=a.insertRow(-1),f=a.style,d=x.style;f.width=d.width;f.height=ka?ka+"px":d.height;f.padding="0";wb(x);x.className=ia.Da;$&&(H=b.insertCell(-1),H.style.whiteSpace="nowrap");C=b.insertCell(-1);
C.className="gsib_a";I.ed()&&S&&(T=S.ja(),R=b.insertCell(-1),R.appendChild(T));c(a,C)}B(a);G=a}function E(){if(aa){var a=x.value.length;fa=Ha(a);ab(x,a)}}function B(a){F.ka(a,"mouseup",function(){x.focus()})}function v(){F.ka(x,"keydown",y);(Za||ia.Kc)&&F.ka(x,"keypress",L);F.ka(x,"select",V,10);var a=u,b=function(b){F.ka(x,b,A,10,a)};b("mousedown");b("keyup");b("keypress");a=n;b("mouseup");b("keydown");b("focus");b("blur");b("cut");b("paste");b("input");F.ka(x,"compositionstart",D);F.ka(x,"compositionend",
D)}function D(a){a=a.type;"compositionstart"==a?I.le(n):"compositionend"==a&&I.le(u)}function y(a){var b=a.keyCode;ja=b;var f=Ab&&eb(b)&&Y.Ba(),d=b==U.ye,c=b==U.Id;ba=u;b==U.ze&&(ba=I.eg());d&&((b=Y.Ia())&&J(b)?Y.Eb(a.shiftKey):F.defer(function(){Y.Eb(a.shiftKey)}));if(f||d||c||ba)a.nc=n}function J(a){return(a=W[a.B()].Fi)&&a()}function L(a){var b=a.keyCode,f=b==U.Id,d=b==U.ze&&ba;if(b==U.ye||f||d)a.nc=n}function A(a){if(!ma){var b=a.hb;if(!b.indexOf("key")&&!a.ctrlKey&&!a.altKey&&!a.shiftKey&&!a.metaKey)a:if(a=
a.keyCode,"keypress"!=b){var f=eb(a),d;if("keydown"==b){if(I.gg(229==a),f)break a}else if(d=a!=ja,ja=-1,!f||d)break a;switch(a){case U.Id:I.Wf();break;case U.Rg:I.Zf();break;case U.Sg:I.$f();break;case U.Tg:Y.hg();break;case U.Qg:I.Vf(fa);break;case U.Vg:I.Uf(fa);break;case U.Ug:I.Tf(fa)}}V();I.Yf(x.value,fa,b)}}function M(){F.ka(x,"focus",function(){aa=n;I.Xf()},99);F.ka(x,"blur",function(){aa=u;I.ke()},99)}function N(){ga||(ga=window.setInterval(ha,ia.Oc||50))}function P(){ga&&(Qa(ga),ga=o)}function ha(){A({hb:"polling"})}
function da(){zb&&mb(x)}function V(){if(aa){var a=bb(x);a&&(fa=a)}}function O(){var a;F.listen(window,"pagehide",function(){ma=n;a=x.value});F.listen(window,"pageshow",function(b){ma=u;b.persisted&&I.Fc(a)})}var U=Ub,I,Y,F,S,W,x,X,na,ia,aa,oa,ga,fa=Ha(0),ja=-1,Q=u,C,G,H,R,T,ba,ma,$,ea,Fa,ka,wa={ga:function(a,b){Fa=a;x=a.oe();ea=a.Jc();a.jg()||b.addRule(".gsib_a","width:100%;vertical-align:top;padding:3px 6px 0")},W:function(a){I=a.get(118,wa);F=a.get(117,wa);Y=a.get(128,wa);S=a.get(173,wa);W=xb(a.la(152,
wa));a=a.Ca();X=a.Za();na=a.oa()},X:function(b){ia=b;ka=b.Mc;aa=db(x);V();$a&&F.ka(x,"beforedeactivate",function(a){Q&&(Q=u,a.nc=n)},10);zb&&O();G=x;$=!!b.ta[130];(I.fg()||I.ed()||$||b.Lc)&&z();x.nfd=n;b.Cb&&(F.ka(x,"blur",P,10),F.ka(x,"focus",N,10),oa=n);F.jc(8,da);v();M();a(b)},O:a,B:function(){return 119},M:function(){return 4},H:function(){return{Hg:c,je:j,va:e,Xa:i,Vc:d,getHeight:b,getWidth:k,Fg:l,Sf:h,me:g,Hc:f,select:q,refresh:r,focus:p,blur:s,Ec:m,clear:t}},fa:function(){oa&&P();ia.yb&&F.Cg(x,
I.ke)}};return wa});
K.register(129,18,function(){function a(a){A=a;var b=a.Ib;b&&(V=L.ne(b));I.className=a.Uc||"gssb_m";x=a.Tc||"gssb_i"}function c(a,b){if(!I)return u;O=b;t();for(var f=u,d=0,c;c=a[d++];)q(c)&&(f=n);return f}function j(a){return y[a.B()].rb(o,a,J)}function e(a){var b=y[a.B()];if(b&&b.Zb){var f=D.ra();return b.Zb(a,f)}return a.Y()}function i(a,b){if(!I)return u;O=b;t();for(var f=u,d=0,c;c=a[d++];)if(1==c)if(F)Y.appendChild(F);else{c=p();var g=c.style;g.textAlign="center";g.whiteSpace="nowrap";c.dir=U;
g=gb();g.style.position="relative";S=gb();S.className="gssb_g";A.La&&(S.style.paddingBottom="1px");r(A.Jb,S,13);A.Qc?r(A.Ea,S,8):A.Rc&&r(A.Sc,S,14);g.appendChild(S);c.appendChild(g);F=c.parentNode}else 2==c?W?Y.appendChild(W):(c=p(),g=c.style,g.padding="1px 4px 2px 0",g.fontSize="11px",g.textAlign="right",g=Ya("a"),g.id="gssb_b",g.href="http://www.google.com/support/websearch/bin/answer.py?hl="+A.Ka+"&answer=106230",g.innerHTML=A.Hb,c.appendChild(g),W=c.parentNode):3==c?(c=ha.pop())?Y.appendChild(c):
(c=I.insertRow(-1),c.Xg=n,c=c.insertCell(-1),g=Ya("div","gssb_l"),c.appendChild(g)):q(c)&&(f=n);return f}function d(a){s(a,x);a={index:a,Gi:B.ha()[a],Hi:da[a]};v.Z(10,a)}function b(a){s(a,"");v.Z(11)}function k(){for(var a,b,f;f=N.pop();)a=f.B(),(b=M[a])||(b=M[a]=[]),b.push(f),a=f.ja(),a.parentNode.removeChild(a);for(;a=Y.firstChild;)a=Y.removeChild(a),a.Xg?ha.push(a):a!=F&&a!=W&&P.push(a);da=[]}function l(a){return(a=da[a])?a.ya():u}function h(){t()}function g(){return I}function f(){return A.Gb||
U==O?V:o}function q(a){var b=a.B(),f=y[b];if(!f)return u;var d=(b=M[b])&&b.pop();d||(d=f.pb(J));f.$(a,d);N.push(d);var b=d.ja(),c=p();c.className="gssb_a "+A.eb;c.appendChild(b);if(a.Ta!==ca){da.push(d);var d=O,g=a.Ta();b.onmouseover=function(){B.og(g)};b.onmouseout=function(){B.ng()};b.onclick=function(b){D.Pb();a.Wc()&&D.$a(a.Y());B.kg(g);b=b||window.event;f.qb(b,a,J)}}else d=U;z(c,d);return n}function r(a,b,f){var d=Ya("input");d.type="button";d.value=Ka(a);d.onclick=function(){J.search(D.ma(),
f)};var c;if(A.Fb){a="lsb";c=Ya("span");var g=Ya("span");c.className="ds";g.className="lsbb";c.appendChild(g);g.appendChild(d)}else a="gssb_h",c=d;d.className=a;b.appendChild(c)}function p(){var a=P.pop();if(a)return Y.appendChild(a),a.firstChild;a=I.insertRow(-1);a=a.insertCell(-1);a.className=A.eb;a.onmousedown=m;return a}function s(a,b){var f=da[a];f&&f.ya()&&(f.ja().parentNode.parentNode.className=b)}function m(a){a=a||window.event;a.stopPropagation?a.stopPropagation():Za||$a&&D.Hc();return u}
function t(){if(S){var a=A.Kb?A.Kb:D.getWidth()-3;0<a&&(S.style.width=a+"px")}}function z(a,b){a.dir!=b&&(a.dir=b,a.style.textAlign=E[b])}var E={rtl:"right",ltr:"left"},B,v,D,y,J,L,A,M={},N=[],P=[],ha=[],da=[],V,O,U,I,Y,F,S,W,x,X={ga:function(a,b){L=a;U=a.Jc();b.addRule(".gssb_a","padding:0 7px");b.addRule(".gssb_a,.gssb_a td","white-space:nowrap;overflow:hidden;line-height:22px");b.addRule("#gssb_b","font-size:11px;color:#36c;text-decoration:none");b.addRule("#gssb_b:hover","font-size:11px;color:#36c;text-decoration:underline");
b.addRule(".gssb_m","color:#000;background:#fff");b.addRule(".gssb_g","text-align:center;padding:8px 0 7px;position:relative");b.addRule(".gssb_h",["font-size:15px;height:28px;margin:0.2em",Ab?";-webkit-appearance:button":""].join(""));b.addRule(".gssb_i","background:#eee");b.addRule(".gss_ifl","visibility:hidden;padding-left:5px");b.addRule(".gssb_i .gss_ifl","visibility:visible");b.addRule("a.gssb_j","font-size:13px;color:#36c;text-decoration:none;line-height:100%");b.addRule("a.gssb_j:hover","text-decoration:underline");
b.addRule(".gssb_l","height:1px;background-color:#e5e5e5")},W:function(a){B=a.get(128,X);v=a.get(117,X);D=a.get(118,X);J=a.get(121,X);y=xb(a.la(152,X))},X:function(b){A=b;I=fb();var f=Ya("tbody");I.appendChild(f);Y=I.getElementsByTagName("tbody")[0];a(b)},O:a,B:function(){return 129},M:function(){return 18},H:function(){return{mg:c,Zb:e,Eb:j,$:i,lg:d,ec:b,clear:k,ya:l,Vb:h,ja:g,fd:f}}};return X});
K.register(116,8,function(){function a(a){s=a;t.style.position=a.kb}function c(a){a!=y&&(y=a,a=a.ja(),J?a!=J&&v.replaceChild(a,J):v.appendChild(a),J=a)}function j(){D||(D=v?Math.max(v.offsetHeight,0):0);return D}function e(a){if(a!=B){var b=E.style;a?(b.width=a+"px",zb&&0<a&&(b.paddingLeft="1px"),z.appendChild(E),v.style.width=""):(z.removeChild(E),b.paddingLeft="",v.style.width="100%");B=a}}function i(a){var b=t;b.dir!=a&&(b.dir=a,b.style.textAlign=f[a])}function d(){k();g(L,n);g(N,n)}function b(){D=
0;g(L,u);g(N,u);p.Z(12)}function k(){D=0;h();if(N){var a=s.gd[0],b=N.style;"relative"!=s.kb&&(b.top=t.style.top,b.left=t.offsetLeft+z.offsetWidth+"px");N.style.height=Math.max(t.offsetHeight+a,0)+"px";a=v.offsetWidth;0<a&&(N.style.width=a+"px")}y&&y.Vb()}function l(a){if(A)M!=a&&A.replaceChild(a,M);else{var b=t.insertRow(-1);b.style.height="0";b.insertCell(-1);A=b.insertCell(-1);q.Wa()||(g(v,u),g(t,n));L=v;A.appendChild(a)}M=a}function h(){var a="relative"==s.kb,b=r.Vc(),f=s.Qb,d=f[0],c=f[1],g=t.style;
a||(g.top=b.Qh+r.getHeight()+d+"px");var e,h;y&&(h=y.fd());h&&(b=cb(h),e=h.offsetWidth);e||(e=r.getWidth());a||(g.left=b.Ph+c+"px");e+=f[2];B?g.width="":0<e&&(t.style.width=e+"px");Wa&&(g.zoom="normal",g.zoom=1)}function g(a,b){a&&(a.style.display=b?"":"none")}var f={rtl:"right",ltr:"left"},q,r,p,s,m,t,z,E,B,v,D,y,J,L,A,M,N,P={ga:function(a,b){b.addRule(".gssb_c","border:0;position:absolute;z-index:989");b.addRule(".gssb_e",["border:1px solid #ccc;border-top-color:#d9d9d9;",b.prefix("box-shadow:0 2px 4px rgba(0,0,0,0.2);"),
"cursor:default"].join(""));b.addRule(".gssb_f","visibility:hidden;white-space:nowrap");b.addRule(".gssb_k","border:0;display:block;position:absolute;top:0;z-index:988")},W:function(a){q=a.get(115,P);r=a.get(118,P);p=a.get(117,P);m=a.Ca().oa()},X:function(b){s=b;B=0;t=fb();t.className="gstl_"+m+" gssb_c";g(t,u);L=t;var f=t.insertRow(-1);z=f.insertCell(-1);z.className="gssb_f";E=gb();v=f.insertCell(-1);v.className="gssb_e";v.style.width="100%";s.hd&&(N=Ya("iframe","gssb_k"),g(N,u),(s.Wb||document.body).appendChild(N));
h();(b.Wb||document.body).appendChild(t);p.jc(8,k);a(b)},O:a,B:function(){return 116},M:function(){return 8},H:function(){return{Ad:c,getHeight:j,ic:l,kc:e,va:i,show:d,Sa:b,Vb:k}}};return P});
K.register(133,21,function(){function a(a){k(a);if(f)for(var b=0;b<f.length;++b)f[b].update(a)}function c(a){var b=g[a.Cf()]||o,d=u;if(b)++q,d=n;else if(f)for(var c=0;c<f.length;++c)if(b=f[c].get(a)){k(b);++r;break}b&&(c=a.ia(),c!=b.ia()?b=Xb(a,c,b.ha(),b.Sd(),b.Ae(),b.qc(),d,b.Ye()):d&&b.Be());return b}function j(){return q}function e(){return r}function i(){r=q=0}function d(a){var b,f,d,c;for(c in g){b=g[c];b=b.ha();for(d=0;f=b[d++];)if(f.B()==a){delete g[c];break}}l()}function b(){g={};l()}function k(a){a&&
a.qc()&&(g[a.za().Cf()]=a)}function l(){if(f)for(var a=0;a<f.length;++a)f[a].reset()}function h(a,b){return b.Ha()-a.Ha()}var g={},f,q,r,p={W:function(a){f=a.la(151,p)},X:function(){f.sort(h);i()},O:function(){i()},B:function(){return 133},M:function(){return 21},H:function(){return{put:a,get:c,Gd:j,Hd:e,Oa:i,$g:d,Zg:b}}};return p});
K.register(136,46,function(){function a(a){l=!!a.ta[136];e(o,n)}function c(a){var a=k.getWidth(a),b=d.Fg();return a<b}function j(a){e(a,n)}function e(a,d){if(l&&c(i.ma())){if(!h||d)b.Z(6,a),h=n}else h&&(b.Z(7),h=u)}var i,d,b,k,l,h=n,g={W:function(a){b=a.get(117,g);i=a.get(118,g);d=a.get(119,g);k=a.get(147,g)},X:function(f){var d=b.jc;d(1,j);d(4,j);d(5,j);d(8,e);a(f)},O:a,B:function(){return 136},M:function(){return 46},H:function(){return{Mi:c}}};return g});
K.register(141,43,function(){function a(){return e}var c,j,e,i,d={ga:function(a){i=a},W:function(a){c=a.get(119,d);j=a.Ca()},X:function(){e=i.get("gs_lc");if(!e){e=gb();e.style.position="relative";var a=j.Za(),d=i.oe().style;2==a&&(d.top="1px",d.overflow="hidden");d.background="transparent url(data:image/gif;base64,R0lGODlhAQABAID/AMDAwAAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw%3D%3D)";d.position="absolute";d.zIndex=6;c.Hg(e)}},B:function(){return 141},M:function(){return 43},H:function(){return{gi:a}}};
return d});K.register(135,38,function(){function a(a){k=!!a.ta[135];a=a.rd||"";h!=a&&(h=a,i.refresh());j()}function c(){return h}function j(){k&&h&&!d.ma()?l||(i.show(),l=n):e()}function e(){l&&(i.Sa(),l=u)}var i,d,b,k,l=n,h,g={W:function(a){i=a.get(140,g);d=a.get(118,g);b=a.get(117,g)},X:function(f){i.va(d.Ob());var c=b.jc;c(6,j);c(4,j);c(5,j);c(7,e);a(f)},O:a,B:function(){return 135},M:function(){return 38},H:function(){return{ma:c}}};return g});
K.register(140,42,function(){function a(){var a=i.ma();f?ib(g,Ja(a)):g.value!=a&&(g.value=a)}function c(){g.style.visibility=""}function j(){g.style.visibility="hidden"}function e(a){f?jb(g,a):g.dir=a}var i,d,b,k,l,h,g,f,q={ga:function(a){l=a},W:function(a){i=a.get(135,q);d=a.get(141,q);b=a.Ca()},X:function(a){h=d.gi();k=b.oa();f=2==b.Za();var c=(f?"gs_htd":"gs_htif")+k,e=l.ne(c);e||(f?e=hb(a.Da,1):(e=Ya("input",a.Da),e.disabled="disabled",e.autocapitalize=e.autocomplete=e.autocorrect="off",wb(e),
a=e.style,a.position="absolute",a.zIndex=1,a.backgroundColor="transparent",a.outline="",Ab&&(a.WebkitTextFillColor="silver")),e.id=c,e.style.color="silver",h.appendChild(e));g=e},B:function(){return 140},M:function(){return 42},H:function(){return{refresh:a,show:c,Sa:j,va:e}}};return q});
K.Pf(191,192,function(){function a(a){var a=e(a),b="";if(a){for(var d=a.length,c=0,g=0,h=0;d--;){g<<=8;g|=a[h++];for(c+=8;6<=c;)var i=g>>c-6&63,b=b+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_".charAt(i),c=c-6}c&&(b+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_".charAt(g<<8>>c+8-6&63))}return b}function c(a){var b=[];if(a)for(var d=0,c=0,g=0;g<a.length;++g){var e=a.charCodeAt(g);if(32>e||127<e||!l[e-32])return[];d<<=6;d|=l[e-32]-1;c+=6;8<=c&&(b.push(d>>c-
8&255),c-=8)}return b}function j(a,c){var g={};g.ea=Array(4);g.buffer=Array(4);g.mi=Array(4);g.padding=Array(64);g.padding[0]=128;for(var e=1;64>e;++e)g.padding[e]=0;i(g);var e=Array(64),h;64<c.length?(i(g),b(g,c),h=k(g)):h=c;for(var m=0;m<h.length;++m)e[m]=h[m]^92;for(m=h.length;64>m;++m)e[m]=92;i(g);for(m=0;64>m;++m)g.buffer[m]=e[m]^106;d(g,g.buffer);g.total=64;b(g,a);h=k(g);i(g);d(g,e);g.total=64;b(g,h);return k(g)}function e(a){if("string"==typeof a){for(var b=Array(a.length),d=0;d<a.length;++d)b[d]=
a.charCodeAt(d);return b}return a}function i(a){a.ea[0]=1732584193;a.ea[1]=4023233417;a.ea[2]=2562383102;a.ea[3]=271733878;a.wc=a.total=0}function d(a,b){for(var d=a.mi,c=0;64>c;c+=4)d[c/4]=b[c]|b[c+1]<<8|b[c+2]<<16|b[c+3]<<24;for(var c=a.ea[0],e=a.ea[1],i=a.ea[2],j=a.ea[3],k,l,B,v=0;64>v;++v)16>v?(k=j^e&(i^j),l=v):32>v?(k=i^j&(e^i),l=5*v+1&15):48>v?(k=e^i^j,l=3*v+5&15):(k=i^(e|~j),l=7*v&15),B=j,j=i,i=e,e=e+(((c+k+g[v]+d[l]&4294967295)<<h[v]|(c+k+g[v]+d[l]&4294967295)>>>32-h[v])&4294967295)&4294967295,
c=B;a.ea[0]=a.ea[0]+c&4294967295;a.ea[1]=a.ea[1]+e&4294967295;a.ea[2]=a.ea[2]+i&4294967295;a.ea[3]=a.ea[3]+j&4294967295}function b(a,b,c){b=e(b);c||(c=b.length);a.total+=c;for(var g=0;g<c;++g)a.buffer[a.wc++]=b[g],64==a.wc&&(d(a,a.buffer),a.wc=0)}function k(a){var c=Array(16),g=8*a.total,e=a.wc;b(a,a.padding,56>e?56-e:64-(e-56));for(var h=56;64>h;++h)a.buffer[h]=g&255,g>>>=8;d(a,a.buffer);for(h=e=0;4>h;++h)for(g=0;32>g;g+=8)c[e++]=a.ea[h]>>g&255;return c}var l=[0,0,0,0,0,0,0,0,0,0,0,0,0,63,0,0,53,
54,55,56,57,58,59,60,61,62,0,0,0,0,0,0,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,0,0,0,0,64,0,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,0,0,0,0,0],h=[7,12,17,22,7,12,17,22,7,12,17,22,7,12,17,22,5,9,14,20,5,9,14,20,5,9,14,20,5,9,14,20,4,11,16,23,4,11,16,23,4,11,16,23,4,11,16,23,6,10,15,21,6,10,15,21,6,10,15,21,6,10,15,21],g=[3614090360,3905402710,606105819,3250441966,4118548399,1200080426,2821735955,4249261313,1770035416,2336552879,4294925233,
2304563134,1804603682,4254626195,2792965006,1236535329,4129170786,3225465664,643717713,3921069994,3593408605,38016083,3634488961,3889429448,568446438,3275163606,4107603335,1163531501,2850285829,4243563512,1735328473,2368359562,4294588738,2272392833,1839030562,4259657740,2763975236,1272893353,4139469664,3200236656,681279174,3936430074,3572445317,76029189,3654602809,3873151461,530742520,3299628645,4096336452,1126891415,2878612391,4237533241,1700485571,2399980690,4293915773,2240044497,1873313359,4264355552,
2734768916,1309151649,4149444226,3174756917,718787259,3951481745];return{B:function(){return 191},M:function(){return 192},H:function(){return{Gf:a,ei:c,fi:j}}}});
var ac=function(a,c,j,e,i,d,b,k){function l(a){B=n;c.Vh(t,h);return rb(a)}function h(){B&&(j.eh(35),a.Rh(),g.onmouseover=g.onmouseout=g.onclick=o,f.style.display="none",q.style.display="",i.ve()==z&&e.ie(),i.Ag()==z&&(i.Bg(),e.vg()),E=u)}var g,f,q,r,p,s,m,t,z,E=n,B=u;(function(){g=gb();var a=fb();g.appendChild(a);f=a.insertRow(-1);var c=f.insertCell(-1);r=Ya("span");c.appendChild(r);if(0!=b){s=Ya("a");s.href="#ps";s.className="gspqs_a gssb_j";var d=f.insertCell(-1);d.appendChild(s);(2==b?d:c).style.width=
"100%";q=a.insertRow(-1);m=q.insertCell(-1);m.className="gspqs_b";m.innerHTML=k;m.colSpan="2"}})();return{ja:function(){return g},B:function(){return 35},ya:function(){return E},$:function(a,c,g,h,i,j){B=u;E=n;t=c;z=g;f.style.display="";r.innerHTML=a;i&&(r.style.color="#52188c");0!=b&&(q.style.display="none",s.innerHTML=h,s.onclick=l);j&&!p&&(p=tb(f),p.onclick=function(a){e.Pb();e.$a(t);d.search(t,9);return rb(a)});j?(p.innerHTML=j+" &raquo;",p.style.display=""):p&&(p.style.display="none")}}};
K.register(152,33,function(){function a(a){f=a.ld;q=a.Tb;r=a.Sb;p=a.kd;s=a.lb?a.Ea:""}function c(a){return ac(b,k,l,h,g,a,f,r)}function j(a,b){b.$(a.vb(),a.Y(),a.Ta(),q,p,s)}function e(a,b,c){c.search(b.Y(),1)}function i(){return"p"}function d(){return 35}var b,k,l,h,g,f,q,r,p,s,m={ga:function(a,b){b.addRule("a.gspqs_a","padding:0 3px 0 8px");b.addRule(".gspqs_b","color:#666;line-height:22px")},W:function(a){l=a.get(123,m);h=a.get(118,m);k=a.get(189,m);b=a.get(127,m);g=a.get(128,m)},X:a,O:a,B:function(){return 152},
M:function(){return 33},H:function(){return{pb:c,$:j,qb:e,rb:Aa,sb:i,wb:d}}};return m});
K.register(189,188,function(){function a(a){b="https:"==document.location.protocol||a.nb;d=a.Pa;a=!!a.ua[35];k=!(!i||!d||!a);l=!b;k&&l&&i.Ff()}function c(a){var c={};if(k)if(b)c.tok=d;else if(q&&g){var e=q.Gf(a),j=q.ei(g),a=q.fi(a,j),a=q.Gf(a);c.qe=e;c.qesig=a;c.pkc=f;k&&l&&h&&828E5<sa()-h&&i.Ff()}return c}function j(a,b){i.Xh(a,b)}function e(a){g=a.websafe_signing_key;f=a.pkc;h=sa()}var i,d,b,k,l,h,g,f,q,r={W:function(a){i=a.get(134,r);q=a.get(191,r)},X:a,O:a,B:function(){return 189},M:function(){return 188},
H:function(){return{$h:c,Vh:j,Yh:e}}};return r});
K.register(134,186,function(){function a(a){g=a.Pa;f=a.authuser;q=a.Fa}function c(){var a=[];Ga("callback","google.sbox.hi"+h,a);e("https://clients1.google.com/complete/init?",a)}function j(a,b){p[a]=b;var c=[];Ga("delq",a,c);Ga("client",q,c);Ga("callback","google.sbox.d"+h,c);e("https://clients1.google.com/complete/deleteitems?",c)}function e(a,b){Ga("tok",g,b);f&&Ga("authuser",f,b);r=Ya("script");r.src=a+b.join("&");k.appendChild(r)}function i(){r&&(k.removeChild(r),r=o)}function d(a){i();l.Yh(a)}
function b(a){i();var a=a[0],b=p[a];b&&(delete p[a],b())}var k=Ra(),l,h,g,f,q,r,p={},s={W:function(a){l=a.get(189,s);h=a.Ca().oa()},X:function(c){var f=window.google.sbox;f["hi"+h]=d;f["d"+h]=b;a(c)},O:a,B:function(){return 134},M:function(){return 186},H:function(){return{Ff:c,Xh:j}},fa:function(){i()}};return s});
K.register(156,187,function(){function a(a){var c=j.$h(a.ia()),b;for(b in c)a.setParameter(b,c[b]);return 1}function c(){return 12}var j,e={W:function(a){j=a.get(189,e)},B:function(){return 156},M:function(){return 187},H:function(){return{Xc:a,Ha:c}}};return e});
K.register(149,180,function(){function a(a){1==a.xa&&(s=a,a=g.zf(),f=a.Ra,q=a.Bf)}function c(a,b,c){d(a.oa(),a.ia(),b,c);return n}function j(){return 1}function e(){return p}function i(a){var b=r[a];b&&(k(b),delete r[a])}function d(a,c,d,g){s.ob||b();var e=l();e&&(e.open("GET",[f,"?",q?q+"&":"",d?d+"&":"","q=",encodeURIComponent(c),"&xhr=t"].join(""),n),e.onreadystatechange=function(){if(4==e.readyState){switch(e.status){case 403:p=1E3;break;case 302:case 500:case 502:case 503:++p;break;case 200:g(eval(e.responseText),
u);default:p=0}i(a)}},r[a]=e,e.send(o))}function b(){for(var a in r)k(r[a]);r={}}function k(a){var b=a.readyState;0!=b&&4!=b&&a.abort();a.onreadystatechange=Aa}function l(){var a=o;$a?a=h("Msxml2")||h("Microsoft"):"undefined"!=typeof XMLHttpRequest&&(a=new XMLHttpRequest);return a}function h(a){var b=o;try{b=new ActiveXObject(a+".XMLHTTP")}catch(c){}return b}var g,f,q,r={},p=0,s,m={W:function(a){g=a.get(127,m)},X:a,O:a,B:function(){return 149},M:function(){return 180},H:function(){return{Ee:c,De:i,
ib:Aa,Vd:j,Od:e}},fa:function(){b();p=0}};return m});K.register(156,49,function(){function a(a){e=!!a.gc[6]}function c(a,c){if(e&&c){var b=c.Zh("i");a.setParameter("mss",b)}return 1}function j(){return 7}var e;return{X:a,O:a,B:function(){return 156},M:function(){return 49},H:function(){return{Xc:c,Ha:j}}}});
K.register(151,97,function(){function a(a){r=a;k=!a.ua[33]}function c(){return 2}function j(a){if(k){var c=a.ha();if(!(c.length>=r.Rb)){var f=a.za().qa();if(c.length){for(var g=0,e;e=c[g];++g){if(!l[e.B()])return;e=e.Y();if(!Pa(e,f,n))return}d(a)}else!r.jd&&!b.test(f)&&d(a)}}}function e(a){if(k){var b,c=a.qa(),d=Math.min(c.length,f);if(d>=g)for(var e;0<d;--d)if(b=h[d])if(e=c.substring(0,d),b=b[e]){c=b;d=c.ha();if(d.length){b=a.ia();e=b.toLowerCase();for(var i=a.qa(),j=c.Sd(),l=r.jb||!c.Fd("k"),p=
[],J=ca,L=ca,A=0,M=0,N=ca;N=d[M++];)L=N.Y(),Pa(L,i,n)&&(J=l?q.bold(e,L):Ja(L),p.push(Yb(J,L,A++,N.B(),N.Ua(),N.Ga())));a=Xb(a,b,p,j,n,c.qc(),n,u)}else a=c;return a}}return o}function i(){h={};g=Number.MAX_VALUE;f=0}function d(a){var b=a.za().qa(),c=b.length;c<g&&(g=c);c>f&&(f=c);var d=h[c];d||(d=h[c]={});d[b]=a}var b=/^[!"#$%'()*,\/:;<=>?[\\\]^`{|}~]+$/,k=n,l,h,g,f,q,r,p={W:function(a){q=a.get(150,p)},X:function(b){l=la([0]);i();a(b)},O:a,B:function(){return 151},M:function(){return 97},H:function(){return{Ha:c,
update:j,get:e,reset:i}},fa:function(){k=u}};return p});
K.register(151,98,function(){function a(a){l=a.jb}function c(){return 3}function j(a){var c=a.za(),e=a.ha();if(e.length){var h=c.qa();a:for(var c=Number.MAX_VALUE,i,j=0;i=e[j++];){if(!d[i.B()]){c=-1;break a}i=i.Y();c=Math.min(i.length,c)}if(-1!=c){var k=e[0].Y();if(Pa(k,h,n))for(j=h.length+1;j<=c;){h=o;for(i=0;k=e[i++];){k=k.Y();if(j>k.length)return;k=k.substr(0,j);if(h){if(h!=k)return}else h=k}b[h]=a;++j}}}}function e(a){var c=b[a.qa()];if(c){var d=a.Af(),e=a.qa();c.za().qa();for(var h=c.Sd(),i=
l||!c.Fd("k"),j=[],t,z,E=c.ha(),B=0,v;v=E[B++];)z=v.Y(),t=i?k.bold(d,z):Ja(z),j.push(Yb(t,z,v.Ta(),v.B(),v.Ua(),v.Ga()));delete b[e];a=Xb(a,a.ia(),j,h,n,c.qc(),n,u)}else a=o;return a}function i(){b={}}var d,b={},k,l,h={W:function(a){k=a.get(150,h)},X:function(b){d=la([0]);a(b)},O:a,B:function(){return 151},M:function(){return 98},H:function(){return{Ha:c,update:j,get:e,reset:i}}};return h});
var bc=function(){var a;a=gb();return{ja:function(){return a},B:function(){return 19},ya:function(){return n},$:function(c,j){a.innerHTML=["<b>",c," = ",j,"</b>"].join("")}}};
K.register(152,35,function(){var a,c;function j(){return bc()}function e(b,d){var e=b.Ga();d.$(e[a],e[c])}function i(a,b,c){c.search(b.Y(),1)}function d(a,b,c){c.search(b.Y(),1);return n}function b(){return"h"}function k(){return 19}a=0;c=1;return{B:function(){return 152},M:function(){return 35},H:function(){return{pb:j,$:e,qb:i,rb:d,sb:b,wb:k}}}});
var cc=function(a,c){var j,e,i,d,b;(function(){j=gb();j.className="gsmq_a";var a=fb();j.appendChild(a);e=a.insertRow(-1);a=e.insertCell(-1);a.style.width="100%";i=Ya("span");a.appendChild(i)})();return{ja:function(){return j},B:function(){return 38},ya:function(){return n},$:function(j,l,h){i.innerHTML=j;b=l;h&&!d&&(d=tb(e),d.onclick=function(d){a.Pb();a.$a(b);c.search(b,9);return rb(d)});h?(d.innerHTML=h+" &raquo;",d.style.display=""):d&&(d.style.display="none")}}};
K.register(152,94,function(){function a(a){k=a.lb?a.Ea:""}function c(a){return cc(b,a)}function j(a,b){b.$(a.vb(),a.Y(),k)}function e(a,b,c){c.search(b.Y(),1)}function i(){return"v"}function d(){return 38}var b,k,l={ga:function(a,b){b.addRule(".gsmq_a","padding:0")},W:function(a){b=a.get(118,l)},X:a,O:a,B:function(){return 152},M:function(){return 94},H:function(){return{pb:c,$:j,qb:e,rb:Aa,sb:i,wb:d}}};return l});
var dc=function(a){function c(a){return l?(rb(a),n):u}function j(b){b=b||window.event;l=u;b.which?l=2==b.which:b.button&&(l=4==b.button);d.href=a.ub(k)}function e(a,b){var c=Ya("span");c.className=a;b.appendChild(c);return c}var i,d,b,k,l;(function(){i=gb();i.className="gsn_a";i.style.lineHeight="117%";var a=e("gsn_b",i);d=Ya("a");a.appendChild(d);a.appendChild(Ya("br"));b=e("gsn_c",a)})();return{ja:function(){return i},B:function(){return 5},ya:function(){return n},$:function(a,e,f,i){d.innerHTML=
a;d.onmousedown=j;d.onclick=c;d.href=f;b.innerHTML=e;k=i}}};
K.register(152,32,function(){var a,c;function j(a){return dc(a)}function e(b,d){var e=b.Ga(),h=e[a],e=e[c],i=b.vb(),j=i.replace(/HTTPS?:\/\//gi,""),i=La(i);/^HTTPS?:\/\//i.test(i)||(i=(0<h.indexOf("/url?url=https:")?"https":"http")+"://"+i);d.$(e,j,i,h)}function i(a,b){return b}function d(a,b,c){return h(a,b,c)}function b(a,b,c){h(a,b,c);return n}function k(){return"n"}function l(){return 5}function h(b,c,d){c=c.Ga()[a];d.tb(c);return rb(b)}a=0;c=1;return{ga:function(a,b){b.addRule(".gsn_a","padding-top:4px;padding-bottom:1px");
b.addRule(".gsn_b","display:block;line-height:16px");b.addRule(".gsn_c","color:green;font-size:13px")},B:function(){return 152},M:function(){return 32},H:function(){return{pb:j,$:e,Zb:i,qb:d,rb:b,sb:k,wb:l}}}});
K.register(152,20,function(){function a(a){k=a.lb?a.Ea:""}function c(a){return ec(b,a)}function j(a,b){b.$(a.vb(),a.Y(),k)}function e(a,b,c){c.search(b.Y(),1)}function i(){return"g"}function d(){return 0}var b,k,l={ga:function(a,b){b.addRule(".gsq_a","padding:0")},W:function(a){b=a.get(118,l)},X:a,O:a,B:function(){return 152},M:function(){return 20},H:function(){return{pb:c,$:j,qb:e,rb:Aa,sb:i,wb:d}}};return l});
var ec=function(a,c){var j,e,i,d,b;(function(){j=gb();j.className="gsq_a";var a=fb();j.appendChild(a);e=a.insertRow(-1);a=e.insertCell(-1);a.style.width="100%";i=Ya("span");a.appendChild(i)})();return{ja:function(){return j},B:function(){return 0},ya:function(){return n},$:function(j,l,h){i.innerHTML=j;b=l;h&&!d&&(d=tb(e),d.onclick=function(d){a.Pb();a.$a(b);c.search(b,9);return rb(d)});h?(d.innerHTML=h+" &raquo;",d.style.display=""):d&&(d.style.display="none")}}};
Db=function(a,c){if(a&&c){var j=a.btnG;j&&c.Jf(j[0]||j,12)}a&&c&&(j=a.btnI)&&c.Jf(j[0]||j,7)};
var fc=function(){function a(a){return{api:a,lh:a.a,O:a.b,fa:a.c,Ui:a.d,jh:a.e,ra:a.f,ma:a.g,Ba:a.h,Ma:a.i,Xe:a.j,kh:a.k,Xi:a.l,Wi:a.m,Jf:a.n,ib:a.o,Si:a.p,he:a.q,Ti:a.r,Qi:a.s,Xb:a.t,ge:a.u,focus:a.v,blur:a.w,re:a.x,Ja:a.y,Fc:a.z,se:a.aa,Oa:a.ab,search:a.ad,Yi:a.ae,$i:a.af,Bb:a.ag,Ia:a.ah,cj:a.ai,fe:a.al,pe:a.am,Oh:a.an,wa:a.ao,Nh:a.ap,Vi:a.aq,Za:a.ar,oa:a.as,Ri:a.at,setSuggestions:a.au,Zi:a.av,Ec:a.aw,ue:a.ax,ic:a.ay}}return{Ya:function(c,j,e,i){try{var d=window.google.sbox(c,j,e,i);return a(d)}catch(b){return o}},
translate:function(c){return a(c.api||c)}}};
(function(){var a=/^\/(search|images)$/,c=/[#&]fp=/,j;Eb=function(){for(var a=["gbqf","f","gs"],c=0,d;d=a[c++];)if(d=document.getElementsByName(d)[0])return d;return o};Fb=function(a,c){google.register(10,{init:a,dispose:c})};Gb=function(){return a.test(window.location.pathname)||c.test(window.location.hash)};Hb=function(){if(!j){var a=google.browser.engine,c=google.browser.product;j={};j[0]=a.IE;j[1]=a.GECKO;j[2]=c.OPERA;j[5]=a.WEBKIT;j[4]=c.SAFARI;j[3]=c.CHROME;j[6]=c.IPAD||c.IPOD||c.IPHONE;j[7]=
c.ANDROID_MOBILE||c.ANDROID_TABLET}return j}})();window.google||(window.google={});
window.google.sbox=function(a,c,j,e){function i(){m.fa()}function d(a){D.Fc(a||"")}function b(){return ha}function k(){return P}function l(){return D.ma()}function h(){B.Z(8)}function g(){return V||!!z&&z.wa()}function f(){if(a)for(var b=a;b=b.parentNode;){var c=b.dir;if(c)return c}return"ltr"}function q(a){a=t.translate(a);a.ua[35]||(a.Pa="");var b=a.fc;b?a.fc=b.toLowerCase():a.md=u;Ib||(a.zb=u);return a}function r(){var a=vb();B.listen(window,"resize",function(){var b=vb();if(b.Ef!=a.Ef||b.Df!=
a.Df)a=b,h()})}function p(a){var b=a.ta,c=b[135],d=b[137],e=b[240],f=b[138],e=d||f||e;b[139]||c||e?(a.ta[136]=n,a.ta[141]=n,e?(a=ra(a.Ka),!d||zb&&(Jb||a)||$a&&a?(ha=3,b[137]=u,b[142]=u):ha=2):ha=1):ha=0}var s,m,t,z,E,B,v,D,y,J,L,A,M,N,P,ha,da=u,V,O={a:function(b){if(!da){var b=q(b),d=yb(a),e=f(),g=!!d.getElementById("gs_id"+P),h=Zb(b.od,b.nd);p(b);V=b.wa;m=Vb(s,b.Yb||{},{jg:function(){return g},get:function(a){return d.getElementById(a+P)},ne:function(a){return d.getElementById(a)},xe:function(){return c},
Jc:function(){return e},oe:function(){return a}},h,O,b);s.Ud(h,g);h.Wh();z=m.get(130,O);E=m.get(115,O);B=m.get(117,O);v=m.get(123,O);D=m.get(118,O);y=m.get(119,O);J=m.get(120,O);L=m.get(126,O);A=m.get(128,O);M=m.get(139,O);N=m.get(121,O);r();da=n}},b:function(a){i();a=q(a);p(a);V=a.wa;m.O(a)},c:i,d:function(){return c},e:function(a,b){return kb(a,b)},f:function(){return D.ra()},g:l,h:function(){return A.Ba()},i:function(){return A.Ma()},j:function(a){return J.Ub(a)},k:function(a,b){a||(a=J.Ub(b));
return Ca(a)},l:function(){return A.Wa()},m:function(){return A.ig()},n:function(a,b){B.listen(a,"click",function(a){N.search(l(),b);return qb(a)})},o:function(){v.ib()},p:function(){A.Gc()},q:function(a){D.he(a||"")},r:function(){return E.getHeight()},s:function(){D.clear()},t:function(a){return v.Xb(a)},u:function(){D.ge()},v:function(){y.focus()},w:function(){y.blur()},x:function(){return v.re()},y:function(){var a=L.Ja();return a?pa(a.We()):o},z:d,aa:function(a){a=v.se(a,o);return pa(a.We())},
ab:function(){J.reset()},ad:function(a,b){N.search(a,b)},ae:function(){M&&M.refresh()},af:function(a){A.$d(a)},ag:function(){A.Bb()},ah:function(){return A.Ia()},ai:h,al:function(){D.fe()},am:function(){return m&&m.pe()},an:function(a){z&&z.Oh(a)},ao:g,ap:function(){return g()&&z?z.Nh():""},aq:function(a,b){return lb(a,b)},ar:b,as:k,at:function(){M&&M.clear()},au:function(a,b){d(a);A.isEnabled()&&A.setSuggestions(a,b,u)},av:function(a){B.Z(16,{Gg:a})},aw:function(){return y.Ec()},ax:function(a){v.ue(a)},
ay:function(a){E.ic(a)},oa:k,Za:b};P=e==o?K.Th():e;t=Sb();s=$b(j);(function(){var a=window.navigator.userAgent,b=s.Td(),c=/Version\/(\d+)/.exec(a),c=c&&c[1];c||(c=(c=/(?:Android|Chrome|Firefox|Opera|MSIE)[\s\/](\d+)/.exec(a))&&c[1]);a=parseInt(c,10)||0;Xa=($a=b[0])&&8>=a;Wa=$a&&7>=a;zb=b[1];Za=b[2];Ab=b[5];Bb=b[4];Ib=b[3];Cb=b[7]})();Jb=/Mac/.test(navigator&&(navigator.platform||navigator.appVersion)||"");return O};
(function(){var a,c,j,e,i;function d(b){var d=Eb(),k=d.q,D=b.ds,y=b.ovr;f=d;q=D;m=b.client;t=b;b=g.Ya();if(s[1]||ra(google.kHL))b.Cb=n;b.Fa=m;b.Lb=q;b.Nb=t.pq||"";b.Pa=t.token||"";b.Ld=u;b.Ab=u;b.Nd=n;b.Va=0;b.Ka=google.kHL;b.authuser=google.authuser;b.Db="lst-t";b.Da="gsfi";b.eb="gsfs";b.Ib="sbhost";t.soff&&(b.Mb=n);b.Gb=u;d=t.msgs;b.Jb=d.srch;b.Ea=d.lcky;b.Hb=d.lml;b.Tb=d.psrl;b.Sb=d.psrc;b.Qa=t.exp||"";b.dc=t.scc||"";t.jsonp?(b.xa=0,b.$b=t.host,b.mb=n):b.xa=1;if(y&&("ca"in y&&(b.Kd=y.ca),"ct"in
y&&(b.Rb=y.ct),"l"in y&&(b.Md=y.l),"lm"in y&&(b.La=y.lm),"ms"in y&&(d=y.ms,b.gc[6]=d,b.ua[38]=d),"p"in y&&(b.ua[35]=y.p),"s"in y&&(b.nb=y.s),"sw"in y))r=y.sw,b.Fb=r;b.Na=n;"i"==q?(b.Na=u,b.La=u):Gb()&&(b.Na=u);b.Yb={135:161,140:161,136:161,141:161};var y=Gb(),d=(D=r&&y)?-1:0,D=[D?0:-1,0,d],J={};J[1]=[y?18:-1,0,d];for(var L in Mb)if(y=Mb[L],s[y]&&5!=y){L=J[y]||D;b.Qb=[L[0],L[1],L[2]];break}L=g.normalize(b);l=h.Ya(k,f,z);l.lh(L);Db(f,l);k=[a,c,j,e,i];for(L=0;b=k[L++];)p[b]=l.jh(f,b);k=google.sn;("webhp"==
k||"imghp"==k)&&l.focus()}function b(a){var b=l.Xe();return a+"&"+l.kh(b)}function k(){var b=function(a){p[a]&&(p[a].value="")};b(a);b(c);b(j);b(e);b(i)}a="oq";c="aq";j="aqi";e="aql";i="gs_l";var l,h,g,f,q,r,p={},s,m="hp",t,z={a:function(){return s},b:function(b,d){var g=l.Xe(d),h=function(a){p[a]&&(p[a].value=g[a])};h(a);h(c);h(j);h(e);h(i);f.submit()},c:function(a){window.location=a},d:function(a){window.location=b(a)},e:b,l:function(){k()},r:function(a,b){b||(a.addRule("a.gspqs_a","padding-left:0"),
a.addRule(".gssb_e","border-top:1px solid #a2bff0;border-right:1px solid #558be3;border-bottom:1px solid #558be3;border-left:1px solid #a2bff0;"),a.addRule(".gssb_i","background:#d5e2ff"))}};s=Hb();google.ac={c:d};h=fc();g=Sb();Fb(d,o);return z})();})();
(function(){var a=google.exportSymbol;if(google.y.first){for(var b=0,c;c=google.y.first[b];++b)c();delete google.y.first}for(b in google.y)google.y[b][1]?google.y[b][1].apply(google.y[b][0]):google.y[b][0].go();a("google.y.x",google.x);google.y.first=[];a("google.x",function(e,d){d&&d.apply(e);return!1});})();
